"""Export the whole compliance schema so you can SEE everything that's in the DB.

Writes, into the CDO Docs folder:
  * CDO Compliance DB - regulations (full).csv   — every reg, every column (raw_text previewed)
  * CDO Compliance DB - sources (full).csv       — the source watch-list
  * CDO Compliance DB - Layout.md                — schema map: tables, columns, types, counts

Run:  python db_export.py
(Read-only. The dashboard's Data Captured tab is the visual view; this is the raw one.)
"""
import csv
import os

from db import get_conn

OUT_DIR = ".."  # AI Scrape Project; CDO Docs is one more level up
DOCS_DIR = "../.."  # CDO Docs


def _cols(cur, table):
    cur.execute(
        "select column_name, data_type from information_schema.columns "
        "where table_schema='compliance' and table_name=%s order by ordinal_position",
        (table,),
    )
    return cur.fetchall()


def export_table_csv(cur, table, path, preview_cols=("raw_text",), preview_len=400):
    cols = [c for c, _ in _cols(cur, table)]
    cur.execute(f"select {', '.join(cols)} from compliance.{table} order by 1")
    rows = cur.fetchall()
    with open(path, "w", newline="", encoding="utf-8-sig") as f:
        w = csv.writer(f)
        w.writerow(cols)
        for r in rows:
            out = []
            for col, val in zip(cols, r):
                if col in preview_cols and isinstance(val, str) and len(val) > preview_len:
                    val = val[:preview_len] + f" …[+{len(val) - preview_len} chars in DB]"
                if isinstance(val, list):
                    val = ", ".join(map(str, val))
                out.append(val)
            w.writerow(out)
    return len(rows)


def main():
    docs = os.path.join(os.path.dirname(os.path.abspath(__file__)), DOCS_DIR)
    with get_conn() as c, c.cursor() as cur:
        cur.execute("select table_name from information_schema.tables "
                    "where table_schema='compliance' order by 1")
        tables = [r[0] for r in cur.fetchall()]

        # CSVs for the two populated tables
        n_reg = export_table_csv(cur, "regulations",
                                 os.path.join(docs, "CDO Compliance DB - regulations (full).csv"))
        n_src = export_table_csv(cur, "sources",
                                 os.path.join(docs, "CDO Compliance DB - sources (full).csv"))

        # Layout doc
        lines = ["# CDO Compliance DB — Layout",
                 "",
                 "Supabase project **CDO** (`ruuufhxrubeckbcvwvcq`, us-east-1) · schema **`compliance`**",
                 f"_Generated by db_export.py_",
                 "",
                 "## Tables"]
        for t in tables:
            cur.execute(f"select count(*) from compliance.{t}")
            n = cur.fetchone()[0]
            lines.append(f"\n### `compliance.{t}` — {n} rows")
            lines.append("| column | type |")
            lines.append("|---|---|")
            for col, dt in _cols(cur, t):
                lines.append(f"| {col} | {dt} |")

        # Breakdowns for regulations
        lines.append("\n## Coverage breakdown — `regulations`")
        for grp, label in [("domain", "By domain"), ("jurisdiction", "By jurisdiction")]:
            cur.execute(f"select {grp}, count(*) from compliance.regulations "
                        f"group by 1 order by 2 desc")
            lines.append(f"\n**{label}**")
            for v, n in cur.fetchall():
                lines.append(f"- {v}: {n}")
        cur.execute("select domain, count(*) filter (where employee_count_min>1) "
                    "from compliance.regulations group by 1 having "
                    "count(*) filter (where employee_count_min>1) > 0 order by 1")
        trg = cur.fetchall()
        if trg:
            lines.append("\n**Domains with headcount triggers (applicability is data)**")
            for v, n in trg:
                lines.append(f"- {v}: {n} rule(s) gated by employee_count_min")

        with open(os.path.join(docs, "CDO Compliance DB - Layout.md"), "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")

    print(f"Exported to CDO Docs:")
    print(f"  CDO Compliance DB - regulations (full).csv   ({n_reg} rows)")
    print(f"  CDO Compliance DB - sources (full).csv       ({n_src} rows)")
    print(f"  CDO Compliance DB - Layout.md                (schema map)")


if __name__ == "__main__":
    main()
