"""Export the whole compliance schema so you can SEE everything that's in the DB.

Writes, into the CDO Docs folder:
  * CDO Compliance DB - regulations (full).csv
  * CDO Compliance DB - sources (full).csv
  * CDO Compliance DB - Layout.md

Run:  python db_export.py
"""
import csv
import os

import db as _db

DOCS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")

REG_COLS = ["id", "jurisdiction", "topic", "title", "summary", "citation",
            "source_url", "status", "raw_text", "content_hash", "source_id",
            "last_reviewed", "domain", "employee_count_min", "applies_when",
            "industries", "updated_at"]
SRC_COLS = ["id", "name", "url", "kind", "jurisdiction", "status", "notes", "last_scraped_at"]

PREVIEW_LEN = 400


def _write_csv(path, cols, rows):
    with open(path, "w", newline="", encoding="utf-8-sig") as f:
        w = csv.writer(f)
        w.writerow(cols)
        for row in rows:
            out = []
            for col in cols:
                val = row.get(col)
                if col == "raw_text" and isinstance(val, str) and len(val) > PREVIEW_LEN:
                    val = val[:PREVIEW_LEN] + f" …[+{len(val) - PREVIEW_LEN} chars in DB]"
                if isinstance(val, list):
                    val = ", ".join(map(str, val))
                out.append(val)
            w.writerow(out)
    return len(rows)


def main():
    regs = _db._rpc("compliance_export_regulations", {}) or []
    srcs = _db._rpc("compliance_export_sources", {}) or []
    tables = _db.list_tables()

    n_reg = _write_csv(os.path.join(DOCS_DIR, "CDO Compliance DB - regulations (full).csv"), REG_COLS, regs)
    n_src = _write_csv(os.path.join(DOCS_DIR, "CDO Compliance DB - sources (full).csv"), SRC_COLS, srcs)

    # Coverage breakdown for Layout.md
    overview = _db._rpc("compliance_overview", {}) or []
    by_domain = {}
    by_jur = {}
    for r in regs:
        by_domain[r.get("domain", "?")] = by_domain.get(r.get("domain", "?"), 0) + 1
        by_jur[r.get("jurisdiction", "?")] = by_jur.get(r.get("jurisdiction", "?"), 0) + 1

    lines = [
        "# CDO Compliance DB — Layout",
        "",
        "Supabase project **CDO** (`ruuufhxrubeckbcvwvcq`, us-east-1) · schema **`compliance`**",
        "_Generated by db_export.py_",
        "",
        "## Tables",
    ]
    counts = {"regulations": len(regs), "sources": len(srcs)}
    for t in tables:
        n = counts.get(t, "?")
        lines.append(f"\n### `compliance.{t}` — {n} rows")

    lines.append("\n## Coverage breakdown — `regulations`")
    lines.append("\n**By domain**")
    for v, n in sorted(by_domain.items(), key=lambda x: -x[1]):
        lines.append(f"- {v}: {n}")
    lines.append("\n**By jurisdiction**")
    for v, n in sorted(by_jur.items(), key=lambda x: -x[1]):
        lines.append(f"- {v}: {n}")

    with open(os.path.join(DOCS_DIR, "CDO Compliance DB - Layout.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Exported to CDO Docs:")
    print(f"  CDO Compliance DB - regulations (full).csv   ({n_reg} rows)")
    print(f"  CDO Compliance DB - sources (full).csv       ({n_src} rows)")
    print(f"  CDO Compliance DB - Layout.md")


if __name__ == "__main__":
    main()
