// AUTO-GENERATED by build_dashboard.py — do not edit by hand.
window.CDO_DATA = {
 "regs": [
  {
   "jur": "CA",
   "cit": "8 CCR § 1514",
   "title": "Personal Protective Devices",
   "topic": "ppe",
   "chars": 2225,
   "url": "https://www.dir.ca.gov/title8/1514.html",
   "hash": "38230f9d44",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 1515",
   "title": "Head Protection",
   "topic": "ppe",
   "chars": 404,
   "url": "https://www.dir.ca.gov/title8/1515.html",
   "hash": "2c0573b5a6",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 1516",
   "title": "Eye and Face Protection",
   "topic": "ppe",
   "chars": 730,
   "url": "https://www.dir.ca.gov/title8/1516.html",
   "hash": "b31d69b3ce",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 1517",
   "title": "Foot Protection",
   "topic": "ppe",
   "chars": 404,
   "url": "https://www.dir.ca.gov/title8/1517.html",
   "hash": "479ff6b40e",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 1520",
   "title": "Hand Protection",
   "topic": "ppe",
   "chars": 504,
   "url": "https://www.dir.ca.gov/title8/1520.html",
   "hash": "f778dd9783",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 1529",
   "title": "Asbestos",
   "topic": "respiratory_hazmat",
   "chars": 111398,
   "url": "https://www.dir.ca.gov/title8/1529.html",
   "hash": "658dff5350",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": "disturbing asbestos-containing materials (common in tear-off)",
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 1532.1",
   "title": "Lead",
   "topic": "respiratory_hazmat",
   "chars": 80397,
   "url": "https://www.dir.ca.gov/title8/1532_1.html",
   "hash": "2a2565f275",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": "disturbing lead-containing materials/coatings",
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 1532.3",
   "title": "Occupational Exposures to Respirable Crystalline Silica",
   "topic": "respiratory_hazmat",
   "chars": 32808,
   "url": "https://www.dir.ca.gov/title8/1532_3.html",
   "hash": "d118e893a0",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": "cutting/grinding/disturbing silica-containing materials",
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 1669",
   "title": "General",
   "topic": "fall_protection",
   "chars": 1289,
   "url": "https://www.dir.ca.gov/title8/1669.html",
   "hash": "e1fc61f626",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 1670",
   "title": "Personal Fall Arrest Systems, Personal Fall Restraint Systems and Positioning Devices",
   "topic": "fall_protection",
   "chars": 10713,
   "url": "https://www.dir.ca.gov/title8/1670.html",
   "hash": "3605ad74d4",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 1671",
   "title": "Safety Nets",
   "topic": "fall_protection",
   "chars": 2546,
   "url": "https://www.dir.ca.gov/title8/1671.html",
   "hash": "0208b14151",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 1724",
   "title": "Roofing--General",
   "topic": "roofing_ops",
   "chars": 4611,
   "url": "https://www.dir.ca.gov/title8/1724.html",
   "hash": "464a3a2059",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 1730",
   "title": "Roof Hazards",
   "topic": "roofing_ops",
   "chars": 7979,
   "url": "https://www.dir.ca.gov/title8/1730.html",
   "hash": "f868b908a6",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 1731",
   "title": "Residential-type Roofing Activities",
   "topic": "roofing_ops",
   "chars": 2991,
   "url": "https://www.dir.ca.gov/title8/1731.html",
   "hash": "9fbe78ea39",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 1950",
   "title": "Scope",
   "topic": "confined_space",
   "chars": 2006,
   "url": "https://www.dir.ca.gov/title8/1950.html",
   "hash": "c096b4781d",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": "entry into a confined space",
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 3203",
   "title": "Injury and Illness Prevention Program",
   "topic": "safety_program",
   "chars": 12812,
   "url": "https://www.dir.ca.gov/title8/3203.html",
   "hash": "e5a02db593",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 3221",
   "title": "Fire Prevention Plan",
   "topic": "fire_safety",
   "chars": 2136,
   "url": "https://www.dir.ca.gov/title8/3221.html",
   "hash": "a94eba2d29",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 3314",
   "title": "The Control of Hazardous Energy for the Cleaning, Repairing, Servicing, Setting-Up, and Adjusting Operations of Prime Movers, Machinery and Equipment, Including Lockout/Tagout",
   "topic": "lockout_tagout",
   "chars": 13987,
   "url": "https://www.dir.ca.gov/title8/3314.html",
   "hash": "bffc0cdc72",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": "servicing/maintaining powered equipment",
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 3380",
   "title": "Personal Protective Devices",
   "topic": "ppe",
   "chars": 5309,
   "url": "https://www.dir.ca.gov/title8/3380.html",
   "hash": "2b8d1a1fc3",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 3395",
   "title": "Heat Illness Prevention in Outdoor Places of Employment",
   "topic": "heat_illness",
   "chars": 18445,
   "url": "https://www.dir.ca.gov/title8/3395.html",
   "hash": "1e3bdb27fc",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": "outdoor work / high-heat conditions",
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 3400",
   "title": "Medical Services and First Aid",
   "topic": "first_aid",
   "chars": 2926,
   "url": "https://www.dir.ca.gov/title8/3400.html",
   "hash": "2a5188da99",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 5144",
   "title": "Respiratory Protective Equipment",
   "topic": "respiratory_hazmat",
   "chars": 49471,
   "url": "https://www.dir.ca.gov/title8/5144.html",
   "hash": "621595a1a7",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": "respirator use required by another standard",
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 5194",
   "title": "Hazard Communication",
   "topic": "hazcom",
   "chars": 62159,
   "url": "https://www.dir.ca.gov/title8/5194.html",
   "hash": "2818801428",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Bus. & Prof. Code § 7065",
   "title": "Contractors' license — examination & issuance (CSLB)",
   "topic": "contractor_license",
   "chars": 3979,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=BPC&sectionNum=7065.",
   "hash": "390d537e5b",
   "domain": "licensing_insurance",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Civ. Code § 3426.1",
   "title": "Trade secrets — Uniform Trade Secrets Act (definitions)",
   "topic": "trade_secrets",
   "chars": 2022,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=CIV&sectionNum=3426.1.",
   "hash": "88f6f986d5",
   "domain": "privacy_conduct",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Gov. Code § 100032",
   "title": "CalSavers — state retirement savings mandate",
   "topic": "calsavers",
   "chars": 4332,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=GOV&sectionNum=100032.",
   "hash": "9d57207e96",
   "domain": "benefits_retirement",
   "minEmp": 1,
   "appliesWhen": "no qualified employer retirement plan offered",
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Gov. Code § 12940",
   "title": "FEHA — unlawful employment practices (discrimination & harassment)",
   "topic": "discrimination",
   "chars": 18481,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=GOV&sectionNum=12940.",
   "hash": "400b821ee6",
   "domain": "harassment_eeo",
   "minEmp": 5,
   "appliesWhen": "employers with 5+ (harassment: any size)",
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Gov. Code § 12945",
   "title": "Pregnancy Disability Leave (PDL)",
   "topic": "family_medical_leave",
   "chars": 4314,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=GOV&sectionNum=12945.",
   "hash": "e636045d59",
   "domain": "leave_benefits",
   "minEmp": 5,
   "appliesWhen": "employers with 5+ employees",
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Gov. Code § 12945.2",
   "title": "California Family Rights Act (CFRA) — job-protected leave",
   "topic": "family_medical_leave",
   "chars": 16721,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=GOV&sectionNum=12945.2.",
   "hash": "ab97fd3e7f",
   "domain": "leave_benefits",
   "minEmp": 5,
   "appliesWhen": "employers with 5+ employees",
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Gov. Code § 12945.7",
   "title": "Bereavement leave (AB 1949)",
   "topic": "bereavement_leave",
   "chars": 4343,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=GOV&sectionNum=12945.7.",
   "hash": "0dbc027732",
   "domain": "leave_benefits",
   "minEmp": 5,
   "appliesWhen": "employers with 5+ employees",
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Gov. Code § 12950.1",
   "title": "Sexual harassment prevention training (SB 1343)",
   "topic": "harassment_training",
   "chars": 12391,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=GOV&sectionNum=12950.1.",
   "hash": "eff7cc2b96",
   "domain": "harassment_eeo",
   "minEmp": 5,
   "appliesWhen": "employers with 5+ employees",
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Gov. Code § 12952",
   "title": "Fair Chance Act — criminal history (ban-the-box)",
   "topic": "fair_chance",
   "chars": 6536,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=GOV&sectionNum=12952.",
   "hash": "5999803b9a",
   "domain": "harassment_eeo",
   "minEmp": 5,
   "appliesWhen": "employers with 5+ employees",
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 1030",
   "title": "Lactation accommodation — break time & private space",
   "topic": "lactation",
   "chars": 633,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=1030.",
   "hash": "eef57a0ebb",
   "domain": "leave_benefits",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 1102.5",
   "title": "Whistleblower protection / anti-retaliation",
   "topic": "whistleblower",
   "chars": 4269,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=1102.5.",
   "hash": "3c399d55ea",
   "domain": "harassment_eeo",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 1182.12",
   "title": "State minimum wage",
   "topic": "minimum_wage",
   "chars": 10442,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=1182.12.",
   "hash": "ccef91dfe2",
   "domain": "wage_hour",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 1198.5",
   "title": "Employee right to inspect personnel records",
   "topic": "personnel_records",
   "chars": 8724,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=1198.5.",
   "hash": "bd31426735",
   "domain": "wage_hour",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 1400",
   "title": "California WARN Act — mass layoff/closure notice",
   "topic": "warn_act",
   "chars": 185,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=1400.",
   "hash": "55384cc812",
   "domain": "workforce_reduction",
   "minEmp": 75,
   "appliesWhen": "75+ employees",
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 1771",
   "title": "Prevailing wages required on public works",
   "topic": "prevailing_wage",
   "chars": 668,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=1771.",
   "hash": "ce5b2b2534",
   "domain": "prevailing_wage",
   "minEmp": 1,
   "appliesWhen": "public works projects",
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 1775",
   "title": "Prevailing wage — penalties for underpayment",
   "topic": "prevailing_wage",
   "chars": 5080,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=1775.",
   "hash": "49a1d4013c",
   "domain": "prevailing_wage",
   "minEmp": 1,
   "appliesWhen": "public works projects",
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 1777.5",
   "title": "Apprenticeship requirements on public works",
   "topic": "prevailing_wage",
   "chars": 13298,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=1777.5.",
   "hash": "25648626f0",
   "domain": "prevailing_wage",
   "minEmp": 1,
   "appliesWhen": "public works projects ≥ $30k",
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 201",
   "title": "Final pay on discharge — wages due immediately",
   "topic": "final_pay",
   "chars": 4560,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=201.",
   "hash": "31f5046e12",
   "domain": "wage_hour",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 202",
   "title": "Final pay on resignation — within 72 hours (immediately if 72h notice)",
   "topic": "final_pay",
   "chars": 4748,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=202.",
   "hash": "9982bf5285",
   "domain": "wage_hour",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 203",
   "title": "Waiting-time penalty — up to 30 days' wages for late final pay",
   "topic": "final_pay",
   "chars": 975,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=203.",
   "hash": "50cefce901",
   "domain": "wage_hour",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 226",
   "title": "Itemized wage statements — required pay-stub line items",
   "topic": "wage_statements",
   "chars": 9461,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=226.",
   "hash": "6acd2ad4d4",
   "domain": "wage_hour",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 230",
   "title": "Jury, witness & victim leave; protected time off",
   "topic": "civic_leave",
   "chars": 11813,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=230.",
   "hash": "5bcc29e845",
   "domain": "leave_benefits",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 230.8",
   "title": "Time off for a child's school activities",
   "topic": "civic_leave",
   "chars": 4510,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=230.8.",
   "hash": "39f69ccda6",
   "domain": "leave_benefits",
   "minEmp": 25,
   "appliesWhen": "employers with 25+ employees",
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 233",
   "title": "Kin care — use of accrued sick leave for family",
   "topic": "paid_sick_leave",
   "chars": 2997,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=233.",
   "hash": "2adb7c3797",
   "domain": "leave_benefits",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 246",
   "title": "Paid sick leave — accrual, use & rate (HWHFA)",
   "topic": "paid_sick_leave",
   "chars": 11928,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=246.",
   "hash": "4e7a90406f",
   "domain": "leave_benefits",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 2775",
   "title": "Independent-contractor ABC test (AB 5 / AB 2257)",
   "topic": "ab5",
   "chars": 2112,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=2775.",
   "hash": "d539cd9109",
   "domain": "worker_classification",
   "minEmp": 1,
   "appliesWhen": "engaging independent contractors",
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 2802",
   "title": "Reimbursement of necessary business expenses",
   "topic": "expense_reimbursement",
   "chars": 1580,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=2802.",
   "hash": "c5d5a51113",
   "domain": "wage_hour",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 2810.5",
   "title": "Wage Theft Prevention Act — written pay notice to employees at hire",
   "topic": "wage_notice",
   "chars": 6883,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=2810.5.",
   "hash": "b7491de653",
   "domain": "wage_hour",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 3700",
   "title": "Workers' compensation insurance — required coverage",
   "topic": "workers_comp",
   "chars": 1773,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=3700.",
   "hash": "2e47081204",
   "domain": "licensing_insurance",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 432.3",
   "title": "Pay scale disclosure / pay transparency",
   "topic": "pay_transparency",
   "chars": 4909,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=432.3.",
   "hash": "79a86fd259",
   "domain": "wage_hour",
   "minEmp": 15,
   "appliesWhen": "pay scale in job postings: 15+ employees",
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 510",
   "title": "Overtime — daily/weekly rates (1.5× after 8h/day & 40h/week, 2× after 12h)",
   "topic": "overtime",
   "chars": 1817,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=510.",
   "hash": "d7d15904dc",
   "domain": "wage_hour",
   "minEmp": 1,
   "appliesWhen": "non-exempt employees",
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 512",
   "title": "Meal periods — 30-min meal by the 5th hour; second meal by the 10th",
   "topic": "meal_rest",
   "chars": 4960,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=512.",
   "hash": "69b8693e3b",
   "domain": "wage_hour",
   "minEmp": 1,
   "appliesWhen": "non-exempt employees; shifts over 5 hours",
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 551",
   "title": "Day of rest — one day's rest in seven",
   "topic": "day_of_rest",
   "chars": 137,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=551.",
   "hash": "d5be4fd03e",
   "domain": "wage_hour",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 6401.9",
   "title": "Workplace Violence Prevention Plan (SB 553)",
   "topic": "workplace_violence",
   "chars": 15891,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=6401.9.",
   "hash": "d245a3597f",
   "domain": "harassment_eeo",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 980",
   "title": "Social media privacy — no access to personal accounts",
   "topic": "social_media",
   "chars": 1739,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=980.",
   "hash": "fd698cd850",
   "domain": "privacy_conduct",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Mil. & Vet. Code § 394",
   "title": "Military leave & protection from discrimination (CA)",
   "topic": "military_leave",
   "chars": 5161,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=MVC&sectionNum=394.",
   "hash": "57025932cb",
   "domain": "leave_benefits",
   "minEmp": 1,
   "appliesWhen": "employees in military service",
   "industries": [
    "all"
   ]
  },
  {
   "jur": "CA",
   "cit": "Cal. Veh. Code § 23123.5",
   "title": "Handheld phone / texting while driving prohibited",
   "topic": "distracted_driving",
   "chars": 2042,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=VEH&sectionNum=23123.5.",
   "hash": "c979aaa7ef",
   "domain": "privacy_conduct",
   "minEmp": 1,
   "appliesWhen": "employees who drive for work",
   "industries": [
    "all"
   ]
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1604.11",
   "title": "Title VII — sexual harassment guidelines",
   "topic": "title_vii",
   "chars": 3822,
   "url": "https://www.ecfr.gov/current/title-29/section-1604.11",
   "hash": "8ae6c21791",
   "domain": "harassment_eeo",
   "minEmp": 15,
   "appliesWhen": "15+ employees",
   "industries": [
    "all"
   ]
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1630.2",
   "title": "ADA — definitions (disability, reasonable accommodation, undue hardship)",
   "topic": "ada",
   "chars": 23794,
   "url": "https://www.ecfr.gov/current/title-29/section-1630.2",
   "hash": "581cb59c83",
   "domain": "harassment_eeo",
   "minEmp": 15,
   "appliesWhen": "15+ employees",
   "industries": [
    "all"
   ]
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1630.9",
   "title": "ADA — reasonable accommodation & not making accommodation",
   "topic": "ada",
   "chars": 1962,
   "url": "https://www.ecfr.gov/current/title-29/section-1630.9",
   "hash": "9fe025a775",
   "domain": "harassment_eeo",
   "minEmp": 15,
   "appliesWhen": "15+ employees",
   "industries": [
    "all"
   ]
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.100",
   "title": "Head protection",
   "topic": "ppe",
   "chars": 1643,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.100",
   "hash": "1be8fc8ac3",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "construction"
   ]
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.101",
   "title": "Hearing protection",
   "topic": "ppe",
   "chars": 410,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.101",
   "hash": "b14d695590",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "construction"
   ]
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.102",
   "title": "Eye and face protection",
   "topic": "ppe",
   "chars": 4561,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.102",
   "hash": "e0ddaaba62",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "construction"
   ]
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.103",
   "title": "Respiratory protection",
   "topic": "respiratory_hazmat",
   "chars": 204,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.103",
   "hash": "3a7acfa9a5",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": "respirator use required by another standard",
   "industries": [
    "construction"
   ]
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.1051",
   "title": "General requirements",
   "topic": "ladders",
   "chars": 1448,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.1051",
   "hash": "ed2706669f",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": "ladder/stairway use on site",
   "industries": [
    "construction"
   ]
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.1053",
   "title": "Ladders",
   "topic": "ladders",
   "chars": 16991,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.1053",
   "hash": "00cc6cef0a",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": "ladder use on site",
   "industries": [
    "construction"
   ]
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.1101",
   "title": "Asbestos",
   "topic": "respiratory_hazmat",
   "chars": 233383,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.1101",
   "hash": "8cb2773b4f",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": "disturbing asbestos-containing materials (common in tear-off)",
   "industries": [
    "construction"
   ]
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.1153",
   "title": "Respirable crystalline silica",
   "topic": "respiratory_hazmat",
   "chars": 82422,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.1153",
   "hash": "e3452174b6",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": "cutting/grinding/disturbing silica-containing materials",
   "industries": [
    "construction"
   ]
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.250",
   "title": "General requirements for storage",
   "topic": "materials_handling",
   "chars": 3585,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.250",
   "hash": "261bd9e6d9",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "construction"
   ]
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.252",
   "title": "Disposal of waste materials",
   "topic": "materials_handling",
   "chars": 1167,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.252",
   "hash": "1783c9c3cb",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "construction"
   ]
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.451",
   "title": "General requirements",
   "topic": "scaffolds",
   "chars": 42764,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.451",
   "hash": "2e5368d536",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": "scaffold use on site",
   "industries": [
    "construction"
   ]
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.500",
   "title": "Scope, application, and definitions applicable to this subpart",
   "topic": "fall_protection",
   "chars": 12826,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.500",
   "hash": "7433366d63",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "construction"
   ]
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.501",
   "title": "Duty to have fall protection",
   "topic": "fall_protection",
   "chars": 10036,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.501",
   "hash": "1e1e212f48",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "construction"
   ]
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.502",
   "title": "Fall protection systems criteria and practices",
   "topic": "fall_protection",
   "chars": 30436,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.502",
   "hash": "4b08f53e33",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "construction"
   ]
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.503",
   "title": "Training requirements",
   "topic": "fall_protection",
   "chars": 3021,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.503",
   "hash": "edb416fbc7",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "construction"
   ]
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.55",
   "title": "Gases, vapors, fumes, dusts, and mists",
   "topic": "respiratory_hazmat",
   "chars": 27902,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.55",
   "hash": "304afd1f94",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "construction"
   ]
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.59",
   "title": "Hazard communication",
   "topic": "hazcom",
   "chars": 199,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.59",
   "hash": "dd5d996398",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "construction"
   ]
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.62",
   "title": "Lead",
   "topic": "respiratory_hazmat",
   "chars": 149552,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.62",
   "hash": "9105c17a4b",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": "disturbing lead-containing materials/coatings",
   "industries": [
    "construction"
   ]
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.95",
   "title": "Criteria for personal protective equipment",
   "topic": "ppe",
   "chars": 3137,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.95",
   "hash": "6a9f5b8dc0",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "construction"
   ]
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.96",
   "title": "Occupational foot protection",
   "topic": "ppe",
   "chars": 222,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.96",
   "hash": "36b202703d",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "construction"
   ]
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 541.100",
   "title": "FLSA — executive exemption (white-collar test)",
   "topic": "flsa_exempt",
   "chars": 1425,
   "url": "https://www.ecfr.gov/current/title-29/section-541.100",
   "hash": "5af123acd3",
   "domain": "wage_hour",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 778.107",
   "title": "FLSA — general overtime pay standard (1.5× after 40h/week)",
   "topic": "flsa_overtime",
   "chars": 1551,
   "url": "https://www.ecfr.gov/current/title-29/section-778.107",
   "hash": "053ea5b73f",
   "domain": "wage_hour",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ]
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 825.100",
   "title": "FMLA — general / the Act in a nutshell",
   "topic": "fmla",
   "chars": 3232,
   "url": "https://www.ecfr.gov/current/title-29/section-825.100",
   "hash": "0e3e50a442",
   "domain": "leave_benefits",
   "minEmp": 50,
   "appliesWhen": "50+ employees within 75 miles",
   "industries": [
    "all"
   ]
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 825.112",
   "title": "FMLA — qualifying reasons for leave",
   "topic": "fmla",
   "chars": 1695,
   "url": "https://www.ecfr.gov/current/title-29/section-825.112",
   "hash": "6311166454",
   "domain": "leave_benefits",
   "minEmp": 50,
   "appliesWhen": "50+ employees within 75 miles",
   "industries": [
    "all"
   ]
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 825.200",
   "title": "FMLA — amount of leave (12 workweeks)",
   "topic": "fmla",
   "chars": 7554,
   "url": "https://www.ecfr.gov/current/title-29/section-825.200",
   "hash": "e9545f9f9a",
   "domain": "leave_benefits",
   "minEmp": 50,
   "appliesWhen": "50+ employees within 75 miles",
   "industries": [
    "all"
   ]
  }
 ],
 "sources": [
  {
   "jur": "Federal",
   "name": "Federal OSHA — 29 CFR Part 1926 (Construction Safety & Health)",
   "kind": "api",
   "url": "https://www.ecfr.gov/current/title-29/part-1926",
   "scraped": "2026-06-09",
   "note": "Source of record for the federal floor. Heat has no specific 1926 standard yet (covered by OSH Act Gen. Duty Clause 5(a)(1); a federal heat rule was proposed in 2024 but is not in the CFR).",
   "n": 20
  },
  {
   "jur": "CA",
   "name": "Cal/OSHA — Title 8 (dir.ca.gov)",
   "kind": "scrape",
   "url": "https://www.dir.ca.gov/title8/",
   "scraped": "2026-06-09",
   "note": "Construction + General Industry Safety Orders — full text scraped.",
   "n": 23
  },
  {
   "jur": "CA",
   "name": "California statutes — leginfo (Labor / Government / B&P Codes)",
   "kind": "scrape",
   "url": "https://leginfo.legislature.ca.gov/faces/codesTOCSelected.xhtml?tocCode=LAB",
   "scraped": "2026-06-09",
   "note": "Authoritative CA statute text from the Legislature, across codes. Backs the non-safety compliance domains (wage/hour, leave, harassment, licensing, prevailing wage).",
   "n": 37
  },
  {
   "jur": "Federal",
   "name": "Federal eCFR — 29 CFR (labor & employment)",
   "kind": "api",
   "url": "https://www.ecfr.gov/current/title-29",
   "scraped": "2026-06-09",
   "note": "eCFR API (no key). Federal employment floor: FMLA 825, FLSA 541/778, ADA 1630, Title VII 1604.",
   "n": 8
  },
  {
   "jur": "Federal",
   "name": "Federal Register — rules & proposed rules (API)",
   "kind": "api",
   "url": "https://www.federalregister.gov/developers/api/v1",
   "scraped": null,
   "note": "JSON, no auth. System of record for federal rule CHANGES; filter agency=OSHA/DOL/EEOC; de-dup by FR document number.",
   "n": 0
  },
  {
   "jur": "Federal",
   "name": "OSHA — News Releases",
   "kind": "rss",
   "url": "https://www.osha.gov/news/newsreleases.xml",
   "scraped": null,
   "note": "RSS feed for OSHA enforcement/guidance news.",
   "n": 0
  },
  {
   "jur": "Federal",
   "name": "US DOL Wage & Hour Division — news",
   "kind": "rss",
   "url": "https://www.dol.gov/agencies/whd/news",
   "scraped": null,
   "note": "FLSA/FMLA enforcement & guidance updates.",
   "n": 0
  },
  {
   "jur": "Federal",
   "name": "EEOC — Press Releases",
   "kind": "rss",
   "url": "https://www.eeoc.gov/newsroom/press-releases",
   "scraped": null,
   "note": "Title VII / ADA / EEO enforcement & guidance.",
   "n": 0
  },
  {
   "jur": "Federal",
   "name": "US DOL — FMLA",
   "kind": "scrape",
   "url": "https://www.dol.gov/agencies/whd/fmla",
   "scraped": null,
   "note": "FMLA guidance, fact sheets, posters.",
   "n": 0
  },
  {
   "jur": "Federal",
   "name": "Regulations.gov — dockets & comments (API)",
   "kind": "api",
   "url": "https://api.regulations.gov/v4",
   "scraped": null,
   "note": "Needs api.data.gov key (stored in .env). Proposed-rule dockets.",
   "n": 0
  },
  {
   "jur": "Federal",
   "name": "Congress.gov — federal statutes (API)",
   "kind": "api",
   "url": "https://api.congress.gov/v3",
   "scraped": null,
   "note": "Needs Congress key (stored in .env). Enacted/amended labor statutes.",
   "n": 0
  },
  {
   "jur": "CA",
   "name": "Cal/OSHA Standards Board — rulemaking",
   "kind": "scrape",
   "url": "https://www.dir.ca.gov/oshsb/oshsb.html",
   "scraped": null,
   "note": "Proposed/approved CA safety standards + hearing agendas (leading indicator of change).",
   "n": 0
  },
  {
   "jur": "CA",
   "name": "CA EDD — news & benefit amounts",
   "kind": "scrape",
   "url": "https://edd.ca.gov/en/about_edd/news_releases/",
   "scraped": null,
   "note": "PFL / SDI benefit amounts & news (UIC sections leginfo won't serve cleanly).",
   "n": 0
  },
  {
   "jur": "CA",
   "name": "CA Civil Rights Department (CRD / DFEH)",
   "kind": "scrape",
   "url": "https://calcivilrights.ca.gov/news",
   "scraped": null,
   "note": "FEHA / CFRA / PDL regulations & guidance.",
   "n": 0
  },
  {
   "jur": "CA",
   "name": "CalChamber — HR Watchdog",
   "kind": "subscription",
   "url": "https://www.calchamber.com/hrwatchdog",
   "scraped": null,
   "note": "PAID feed — no scraping; secondary signal only.",
   "n": 0
  },
  {
   "jur": "CA",
   "name": "IWC Wage Orders (Wage Order 16 — construction)",
   "kind": "scrape",
   "url": "https://www.dir.ca.gov/iwc/WageOrderIndustries.htm",
   "scraped": null,
   "note": "Wage Order 16 governs on-site construction (meal/rest/OT for roofing). PDF — needs PDF parse.",
   "n": 0
  },
  {
   "jur": "CA",
   "name": "CSLB — Contractors State License Board",
   "kind": "scrape",
   "url": "https://www.cslb.ca.gov",
   "scraped": null,
   "note": "C-39 roofing license + bond requirements & disciplinary rule changes.",
   "n": 0
  },
  {
   "jur": "Industry",
   "name": "NRCA — National Roofing Contractors Assoc.",
   "kind": "scrape",
   "url": "https://www.nrca.net",
   "scraped": null,
   "note": "ROOFING — newsletter + standards/best practices (our launch industry).",
   "n": 0
  },
  {
   "jur": "Industry",
   "name": "ABC — Associated Builders & Contractors",
   "kind": "scrape",
   "url": "https://www.abc.org",
   "scraped": null,
   "note": "Construction (general) — safety council updates.",
   "n": 0
  },
  {
   "jur": "Industry",
   "name": "PHCC — Plumbing-Heating-Cooling Contractors",
   "kind": "scrape",
   "url": "https://www.phccweb.org",
   "scraped": null,
   "note": "Plumbing — future industry (not active for roofing).",
   "n": 0
  },
  {
   "jur": "Industry",
   "name": "ACCA — Air Conditioning Contractors",
   "kind": "scrape",
   "url": "https://www.acca.org",
   "scraped": null,
   "note": "HVAC — future industry (not active for roofing).",
   "n": 0
  },
  {
   "jur": "Industry",
   "name": "IAPMO — Uniform Plumbing Code",
   "kind": "scrape",
   "url": "https://www.iapmo.org",
   "scraped": null,
   "note": "Plumbing — future industry (not active for roofing).",
   "n": 0
  }
 ],
 "topic": {
  "fall_protection": {
   "n": "Fall Protection",
   "c": "#ff6b6b"
  },
  "roofing_ops": {
   "n": "Roofing Ops",
   "c": "#f5b301"
  },
  "heat_illness": {
   "n": "Heat Illness",
   "c": "#f97316"
  },
  "respiratory_hazmat": {
   "n": "Respiratory / Hazmat",
   "c": "#a855f7"
  },
  "ppe": {
   "n": "PPE",
   "c": "#22d3ee"
  },
  "materials_handling": {
   "n": "Materials / Debris",
   "c": "#34d399"
  },
  "ladders": {
   "n": "Ladders",
   "c": "#60a5fa"
  },
  "scaffolds": {
   "n": "Scaffolds",
   "c": "#818cf8"
  },
  "hazcom": {
   "n": "HazCom",
   "c": "#fbbf24"
  },
  "safety_program": {
   "n": "IIPP / Safety Program",
   "c": "#14b8a6"
  },
  "lockout_tagout": {
   "n": "Lockout/Tagout",
   "c": "#f472b6"
  },
  "fire_safety": {
   "n": "Fire Safety",
   "c": "#fb7185"
  },
  "first_aid": {
   "n": "First Aid",
   "c": "#4ade80"
  },
  "confined_space": {
   "n": "Confined Space",
   "c": "#94a3b8"
  },
  "overtime": {
   "n": "Overtime",
   "c": "#2dd4bf"
  },
  "meal_rest": {
   "n": "Meal & Rest",
   "c": "#5eead4"
  },
  "wage_statements": {
   "n": "Wage Statements",
   "c": "#38bdf8"
  },
  "final_pay": {
   "n": "Final Pay",
   "c": "#a78bfa"
  },
  "minimum_wage": {
   "n": "Minimum Wage",
   "c": "#84cc16"
  },
  "wage_notice": {
   "n": "Wage Theft Notice",
   "c": "#f0abfc"
  },
  "paid_sick_leave": {
   "n": "Paid Sick Leave",
   "c": "#fcd34d"
  },
  "family_medical_leave": {
   "n": "Family/Medical Leave",
   "c": "#fca5a5"
  },
  "bereavement_leave": {
   "n": "Bereavement",
   "c": "#d8b4fe"
  },
  "civic_leave": {
   "n": "Jury/Civic Leave",
   "c": "#93c5fd"
  },
  "discrimination": {
   "n": "FEHA / Discrimination",
   "c": "#f9a8d4"
  },
  "harassment_training": {
   "n": "Harassment Training",
   "c": "#fdba74"
  },
  "workplace_violence": {
   "n": "Workplace Violence",
   "c": "#e879f9"
  },
  "workers_comp": {
   "n": "Workers' Comp",
   "c": "#67e8f9"
  },
  "contractor_license": {
   "n": "Contractor License",
   "c": "#facc15"
  },
  "prevailing_wage": {
   "n": "Prevailing Wage",
   "c": "#bef264"
  },
  "fmla": {
   "n": "FMLA (federal)",
   "c": "#f87171"
  },
  "flsa_overtime": {
   "n": "FLSA Overtime",
   "c": "#06b6d4"
  },
  "flsa_exempt": {
   "n": "FLSA Exemptions",
   "c": "#0ea5e9"
  },
  "ada": {
   "n": "ADA (federal)",
   "c": "#c084fc"
  },
  "title_vii": {
   "n": "Title VII",
   "c": "#ec4899"
  },
  "expense_reimbursement": {
   "n": "Expense Reimbursement",
   "c": "#34d399"
  },
  "day_of_rest": {
   "n": "Day of Rest",
   "c": "#a3e635"
  },
  "pay_transparency": {
   "n": "Pay Transparency",
   "c": "#fde047"
  },
  "personnel_records": {
   "n": "Personnel Records",
   "c": "#7dd3fc"
  },
  "lactation": {
   "n": "Lactation",
   "c": "#fbcfe8"
  },
  "military_leave": {
   "n": "Military Leave",
   "c": "#86efac"
  },
  "fair_chance": {
   "n": "Fair Chance / Ban-Box",
   "c": "#fca5a5"
  },
  "whistleblower": {
   "n": "Whistleblower",
   "c": "#fde68a"
  },
  "ab5": {
   "n": "Worker Classification",
   "c": "#c4b5fd"
  },
  "calsavers": {
   "n": "CalSavers Retirement",
   "c": "#6ee7b7"
  },
  "social_media": {
   "n": "Social Media Privacy",
   "c": "#93c5fd"
  },
  "trade_secrets": {
   "n": "Trade Secrets",
   "c": "#d4d4d8"
  },
  "distracted_driving": {
   "n": "Distracted Driving",
   "c": "#fdba74"
  },
  "warn_act": {
   "n": "WARN Act (layoffs)",
   "c": "#f9a8d4"
  }
 },
 "crit30": [
  {
   "n": "01",
   "p": "IIPP — Injury & Illness Prevention Program",
   "cit": "8 CCR § 3203",
   "st": "ok",
   "our": "8 CCR § 3203 ✓"
  },
  {
   "n": "02",
   "p": "Heat Illness Prevention",
   "cit": "8 CCR § 3395",
   "st": "ok",
   "our": "8 CCR § 3395 ✓"
  },
  {
   "n": "03",
   "p": "Fall Protection in Construction",
   "cit": "8 CCR § 1670",
   "st": "ok",
   "our": "8 CCR § 1670 ✓"
  },
  {
   "n": "04",
   "p": "Respiratory Protection",
   "cit": "8 CCR § 5144",
   "st": "ok",
   "our": "8 CCR § 5144 ✓"
  },
  {
   "n": "05",
   "p": "Confined Space Entry (construction)",
   "cit": "8 CCR § 1950",
   "st": "ok",
   "our": "8 CCR § 1950 ✓"
  },
  {
   "n": "06",
   "p": "Hazard Communication / HazCom",
   "cit": "8 CCR § 5194",
   "st": "ok",
   "our": "8 CCR § 5194 ✓"
  },
  {
   "n": "07",
   "p": "PPE — Personal Protective Equipment",
   "cit": "8 CCR § 3380",
   "st": "ok",
   "our": "8 CCR § 3380 ✓"
  },
  {
   "n": "08",
   "p": "Lockout / Tagout",
   "cit": "8 CCR § 3314",
   "st": "ok",
   "our": "8 CCR § 3314 ✓"
  },
  {
   "n": "09",
   "p": "Fire Safety",
   "cit": "8 CCR § 3221",
   "st": "ok",
   "our": "8 CCR § 3221 ✓"
  },
  {
   "n": "10",
   "p": "First Aid + CPR readiness",
   "cit": "8 CCR § 3400",
   "st": "ok",
   "our": "8 CCR § 3400 ✓"
  }
 ],
 "generatedAt": "2026-06-10 09:57",
 "counts": {
  "total": 88,
  "ca": 60,
  "federal": 28,
  "topics": 49,
  "chars": 1315608,
  "crit30_ok": 10,
  "crit30_total": 10
 },
 "domains": [
  "benefits_retirement",
  "harassment_eeo",
  "leave_benefits",
  "licensing_insurance",
  "prevailing_wage",
  "privacy_conduct",
  "safety",
  "wage_hour",
  "worker_classification",
  "workforce_reduction"
 ]
};
