// AUTO-GENERATED by build_dashboard.py — do not edit by hand.
window.CDO_DATA = {
 "regs": [
  {
   "jur": "CA",
   "cit": "8 CCR § 1514",
   "title": "Personal Protective Devices",
   "topic": "ppe",
   "chars": 2225,
   "url": "https://www.dir.ca.gov/title8/1514.html",
   "hash": "38230f9d44",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "The construction-orders PPE hook: requires employers to provide and require the use of personal protective equipment per the General Industry Safety Orders (Article 10, §3380+). The detailed head/eye/hand/foot requirements live in the §3380-series — the old construction-specific PPE sections (§1515–1520) were repealed."
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 1529",
   "title": "Asbestos",
   "topic": "respiratory_hazmat",
   "chars": 111398,
   "url": "https://www.dir.ca.gov/title8/1529.html",
   "hash": "658dff5350",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": "disturbing asbestos-containing materials (common in tear-off)",
   "industries": [
    "all"
   ],
   "explainer": "California's construction asbestos standard. Old roofs (mastics, felts, transite, pre-1981 materials) routinely contain asbestos — this section sets exposure limits (PEL 0.1 f/cc), work classifications (Class I–IV), required wet methods, respirators, medical surveillance, and the requirement to presume asbestos in pre-1981 materials until tested. Disturbing old roofing without an asbestos determination is a serious-citation risk."
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 1532.1",
   "title": "Lead",
   "topic": "respiratory_hazmat",
   "chars": 80397,
   "url": "https://www.dir.ca.gov/title8/1532_1.html",
   "hash": "2a2565f275",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": "disturbing lead-containing materials/coatings",
   "industries": [
    "all"
   ],
   "explainer": "California's construction lead standard. Lead shows up in old flashing, solder, and paints disturbed during tear-off. Sets a PEL of 50 µg/m³ (8-hr TWA), trigger tasks that require interim protection (respirators, change areas, blood-lead monitoring) until exposure is assessed, plus hygiene and training requirements. CDPH work-practice rules ride on top of it."
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 1532.3",
   "title": "Occupational Exposures to Respirable Crystalline Silica",
   "topic": "respiratory_hazmat",
   "chars": 32808,
   "url": "https://www.dir.ca.gov/title8/1532_3.html",
   "hash": "d118e893a0",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": "cutting/grinding/disturbing silica-containing materials",
   "industries": [
    "all"
   ],
   "explainer": "California's respirable crystalline silica standard for construction. Cutting/grinding tile, concrete, or fiber-cement triggers it. PEL 50 µg/m³, Action Level 25 µg/m³. Employers either follow Table 1's specified controls per task (wet saws, vacuum shrouds, respirators) or do their own air monitoring. Above the PEL 30+ days/year → medical surveillance. A written Exposure Control Plan is mandatory."
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 1669",
   "title": "General",
   "topic": "fall_protection",
   "chars": 1289,
   "url": "https://www.dir.ca.gov/title8/1669.html",
   "hash": "e1fc61f626",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "The general California fall-protection rule for construction: workers exposed to falls must be protected by an approved system (guardrails, personal fall arrest/restraint, or positioning devices). It's the umbrella section that the more specific roofing rules (§1724/1730/1731) hang from. If a crew member can fall and no system is in place, this is the section Cal/OSHA cites."
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 1670",
   "title": "Personal Fall Arrest Systems, Personal Fall Restraint Systems and Positioning Devices",
   "topic": "fall_protection",
   "chars": 10713,
   "url": "https://www.dir.ca.gov/title8/1670.html",
   "hash": "3605ad74d4",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "The nuts-and-bolts requirements for personal fall arrest, fall restraint, and positioning systems in California construction: full-body harness required, anchorage strength minimums (5,000 lbs or engineered 2:1 safety factor), max free-fall distance, inspection before each use, and removal from service after a fall. This is the standard your harness/lanyard/anchor program must satisfy on every roof."
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 1671",
   "title": "Safety Nets",
   "topic": "fall_protection",
   "chars": 2546,
   "url": "https://www.dir.ca.gov/title8/1671.html",
   "hash": "0208b14151",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "Safety-net requirements when nets are the chosen fall protection: where nets may be used, how far below the work surface they may hang, mesh/border strength, and drop-testing. Mostly relevant on larger commercial jobs — but if a net is on site, this is its rulebook."
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 1724",
   "title": "Roofing--General",
   "topic": "roofing_ops",
   "chars": 4611,
   "url": "https://www.dir.ca.gov/title8/1724.html",
   "hash": "464a3a2059",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "The general roofing-operations article for California: requirements that apply to ALL roofing work — surface inspection before work starts, material handling and staging on roofs, and weather/access precautions. It is the entry point for Cal/OSHA's roofing-specific rules."
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 1730",
   "title": "Roof Hazards",
   "topic": "roofing_ops",
   "chars": 7979,
   "url": "https://www.dir.ca.gov/title8/1730.html",
   "hash": "f868b908a6",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "California's 'roof hazards' standard for non-residential roofing: defines when fall protection is required by roof slope and height, warning lines, hoisting areas, and roof-edge rules. Together with §1731 it is the controlling CA authority for roof tear-off fall protection — stricter than the federal floor."
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 1731",
   "title": "Residential-type Roofing Activities",
   "topic": "roofing_ops",
   "chars": 2991,
   "url": "https://www.dir.ca.gov/title8/1731.html",
   "hash": "9fbe78ea39",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "Residential-type roofing in California, explicitly including roof REMOVAL/tear-off. Key numbers (amended eff. July 1, 2025): slopes steeper than 7:12 need fall protection at ANY height; 0:12–7:12 slopes need it at 6 ft. This is the single most directly applicable fall rule for a residential tear-off crew."
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 1950",
   "title": "Scope",
   "topic": "confined_space",
   "chars": 2006,
   "url": "https://www.dir.ca.gov/title8/1950.html",
   "hash": "c096b4781d",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": "entry into a confined space",
   "industries": [
    "all"
   ],
   "explainer": "Confined Spaces in Construction (Article 37, §§1950–1962, updated eff. Jan 1, 2026): scope section for the construction-specific confined-space rules — identification of spaces, entry permits, atmospheric testing, attendants, and rescue. For roofing this hits attics, plenums, tanks, and mechanical penthouses. Do NOT cite general-industry §5157 for construction work."
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 3203",
   "title": "Injury and Illness Prevention Program",
   "topic": "safety_program",
   "chars": 12812,
   "url": "https://www.dir.ca.gov/title8/3203.html",
   "hash": "e5a02db593",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "THE foundational California safety requirement: every employer must have a written, site-implemented Injury & Illness Prevention Program (IIPP) — responsible person named, hazard inspections on a schedule, accident investigation, hazard correction, training at hire/new task/new hazard, and a way for workers to report hazards without fear. It's Cal/OSHA's most-cited standard; an inspector asks for the IIPP first, on every visit."
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 3221",
   "title": "Fire Prevention Plan",
   "topic": "fire_safety",
   "chars": 2136,
   "url": "https://www.dir.ca.gov/title8/3221.html",
   "hash": "a94eba2d29",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "Written Fire Prevention Plan: identify ignition sources and fuel hazards (torch-applied roofing, kettles, fuel storage), housekeeping to control them, maintenance of heat-producing equipment, and employee training on fire hazards of their work. Pairs with hot-work practices on torch-down jobs."
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 3314",
   "title": "The Control of Hazardous Energy for the Cleaning, Repairing, Servicing, Setting-Up, and Adjusting Operations of Prime Movers, Machinery and Equipment, Including Lockout/Tagout",
   "topic": "lockout_tagout",
   "chars": 13987,
   "url": "https://www.dir.ca.gov/title8/3314.html",
   "hash": "bffc0cdc72",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": "servicing/maintaining powered equipment",
   "industries": [
    "all"
   ],
   "explainer": "Lockout/Tagout — controlling hazardous energy when cleaning, servicing, or adjusting machinery and equipment. For roofing: conveyors, hoists, kettles, and powered equipment must be de-energized and locked/tagged before service. Requires written procedures, training, and periodic inspection of the program."
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 3380",
   "title": "Personal Protective Devices",
   "topic": "ppe",
   "chars": 5309,
   "url": "https://www.dir.ca.gov/title8/3380.html",
   "hash": "2b8d1a1fc3",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "California's umbrella PPE rule (GISO Article 10): employers must assess hazards, select and provide appropriate PPE at no cost to the worker, ensure it fits, and train on its use. The specific body-part standards (§3381–3385) hang off this section. This is the Critical-30 PPE citation."
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 3381",
   "title": "Head Protection",
   "topic": "ppe",
   "chars": 3336,
   "url": "https://www.dir.ca.gov/title8/3381.html",
   "hash": "04d5d8ed4a",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "Hard-hat requirement: head protection (ANSI Z89.1) must be worn where there's risk of impact, falling/flying objects, or electrical shock — which describes essentially every active tear-off site with debris coming off a roof. Employer provides; employer enforces."
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 3382",
   "title": "Eye and Face Protection",
   "topic": "ppe",
   "chars": 5839,
   "url": "https://www.dir.ca.gov/title8/3382.html",
   "hash": "5ab7231d43",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "Eye and face protection (ANSI Z87.1): required for flying particles, dust, and chemical exposure — nailing, cutting, grinding, demo work. Includes side-protection and prescription-lens accommodation requirements. This GISO section replaced the repealed construction §1516."
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 3383",
   "title": "Body Protection",
   "topic": "ppe",
   "chars": 598,
   "url": "https://www.dir.ca.gov/title8/3383.html",
   "hash": "3f67aab4c8",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "Body protection: appropriate clothing/protective garments for the hazard — e.g., protection against hot asphalt/tar in built-up roofing, abrasion, and sun exposure. Selection follows the §3380 hazard assessment."
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 3384",
   "title": "Hand Protection",
   "topic": "ppe",
   "chars": 2066,
   "url": "https://www.dir.ca.gov/title8/3384.html",
   "hash": "c11c2f077c",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "Hand protection: gloves matched to the hazard — cut resistance for sheet metal/demo, heat resistance for hot work, chemical resistance for adhesives/solvents. Replaced the repealed construction §1520."
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 3385",
   "title": "Foot Protection",
   "topic": "ppe",
   "chars": 1975,
   "url": "https://www.dir.ca.gov/title8/3385.html",
   "hash": "d8c74bd12b",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "Foot protection (ASTM F2413): protective footwear where falling/rolling objects, punctures (nails — ubiquitous on tear-off), or hot surfaces are present. Replaced the repealed construction §1517."
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 3395",
   "title": "Heat Illness Prevention in Outdoor Places of Employment",
   "topic": "heat_illness",
   "chars": 18445,
   "url": "https://www.dir.ca.gov/title8/3395.html",
   "hash": "1e3bdb27fc",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": "outdoor work / high-heat conditions",
   "industries": [
    "all"
   ],
   "explainer": "California's outdoor Heat Illness Prevention standard — there is NO federal equivalent yet. Requires: fresh water (1 qt/hr per worker), shade at 80°F+, a written Heat Illness Prevention Plan, training, and HIGH-HEAT procedures at 95°F+ (mandatory rest/water breaks, observation, communication). Roofing is one of the highest-risk trades; Cal/OSHA actively enforces this every summer."
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 3400",
   "title": "Medical Services and First Aid",
   "topic": "first_aid",
   "chars": 2926,
   "url": "https://www.dir.ca.gov/title8/3400.html",
   "hash": "2a5188da99",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "Medical services & first aid: a person trained in first aid must be AVAILABLE on every jobsite, suitable first-aid kits on site, and (where no infirmary/clinic is near) written emergency procedures. For dispersed roofing crews this effectively means first-aid/CPR training for foremen — which is exactly how the Critical-30 maps it."
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 5144",
   "title": "Respiratory Protective Equipment",
   "topic": "respiratory_hazmat",
   "chars": 49471,
   "url": "https://www.dir.ca.gov/title8/5144.html",
   "hash": "621595a1a7",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": "respirator use required by another standard",
   "industries": [
    "all"
   ],
   "explainer": "California's respiratory-protection program standard (mirrors federal 1910.134). If ANY task requires a respirator — asbestos, silica, lead dust — this section requires a written program, medical evaluation BEFORE first use, annual fit testing, training, and cleaning/storage rules. Handing a worker an N95 or half-face respirator without the program is itself a violation."
  },
  {
   "jur": "CA",
   "cit": "8 CCR § 5194",
   "title": "Hazard Communication",
   "topic": "hazcom",
   "chars": 62159,
   "url": "https://www.dir.ca.gov/title8/5194.html",
   "hash": "2818801428",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "California's Hazard Communication standard (controlling over federal HazCom in CA, and adds Prop 65). Requires: a written HazCom program, a chemical inventory, Safety Data Sheets accessible to workers, GHS labeling, and training on every hazardous chemical on site — adhesives, primers, solvents, hot asphalt. Construction-specific provisions at (f)(7)."
  },
  {
   "jur": "CA",
   "cit": "Cal. Bus. & Prof. Code § 7065",
   "title": "Contractors' license — examination & issuance (CSLB)",
   "topic": "contractor_license",
   "chars": 3979,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=BPC&sectionNum=7065.",
   "hash": "390d537e5b",
   "domain": "licensing_insurance",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "CSLB licensing — the examination/experience requirements to hold a contractor's license. For a roofing company the operative license is the C-39 classification; an expired or suspended license makes every contract potentially unenforceable and all work unlicensed contracting."
  },
  {
   "jur": "CA",
   "cit": "Cal. Civ. Code § 3426.1",
   "title": "Trade secrets — Uniform Trade Secrets Act (definitions)",
   "topic": "trade_secrets",
   "chars": 2022,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=CIV&sectionNum=3426.1.",
   "hash": "88f6f986d5",
   "domain": "privacy_conduct",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "Uniform Trade Secrets Act definitions: what qualifies as a trade secret (economic value from secrecy + reasonable efforts to keep secret) and what 'misappropriation' means. The legal basis for confidentiality provisions protecting customer lists and bid pricing."
  },
  {
   "jur": "CA",
   "cit": "Cal. Gov. Code § 100032",
   "title": "CalSavers — state retirement savings mandate",
   "topic": "calsavers",
   "chars": 4332,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=GOV&sectionNum=100032.",
   "hash": "9d57207e96",
   "domain": "benefits_retirement",
   "minEmp": 1,
   "appliesWhen": "no qualified employer retirement plan offered",
   "industries": [
    "all"
   ],
   "explainer": "CalSavers: every CA employer with ≥1 eligible employee must either offer a qualified retirement plan or register for the state CalSavers program and facilitate payroll deductions. Penalties of $250–$500 per eligible employee for ignoring it."
  },
  {
   "jur": "CA",
   "cit": "Cal. Gov. Code § 12940",
   "title": "FEHA — unlawful employment practices (discrimination & harassment)",
   "topic": "discrimination",
   "chars": 18481,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=GOV&sectionNum=12940.",
   "hash": "400b821ee6",
   "domain": "harassment_eeo",
   "minEmp": 5,
   "appliesWhen": "employers with 5+ (harassment: any size)",
   "industries": [
    "all"
   ],
   "explainer": "FEHA — California's main anti-discrimination/harassment statute, stronger than federal law: protected classes include race, religion, sex/gender identity, sexual orientation, age 40+, disability, and more; applies at 5+ employees (harassment: ANY size); imposes a standalone duty to take reasonable steps to PREVENT harassment; personal liability possible for harassers. This is the statute behind most CA employment lawsuits."
  },
  {
   "jur": "CA",
   "cit": "Cal. Gov. Code § 12945",
   "title": "Pregnancy Disability Leave (PDL)",
   "topic": "family_medical_leave",
   "chars": 4314,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=GOV&sectionNum=12945.",
   "hash": "e636045d59",
   "domain": "leave_benefits",
   "minEmp": 5,
   "appliesWhen": "employers with 5+ employees",
   "industries": [
    "all"
   ],
   "explainer": "Pregnancy Disability Leave: up to 4 MONTHS of job-protected leave per pregnancy for disability from pregnancy/childbirth, at 5+ employees — separate from, and in ADDITION to, CFRA bonding leave. Also requires reasonable accommodation (e.g., modified duties) for pregnant employees."
  },
  {
   "jur": "CA",
   "cit": "Cal. Gov. Code § 12945.2",
   "title": "California Family Rights Act (CFRA) — job-protected leave",
   "topic": "family_medical_leave",
   "chars": 16721,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=GOV&sectionNum=12945.2.",
   "hash": "ab97fd3e7f",
   "domain": "leave_benefits",
   "minEmp": 5,
   "appliesWhen": "employers with 5+ employees",
   "industries": [
    "all"
   ],
   "explainer": "CFRA — California's family/medical leave, applying at just 5 EMPLOYEES (vs FMLA's 50): up to 12 weeks of job-protected leave for the employee's or a family member's serious health condition or for bonding, with a broader family-member definition than FMLA (includes siblings, grandparents, parents-in-law, designated persons)."
  },
  {
   "jur": "CA",
   "cit": "Cal. Gov. Code § 12945.7",
   "title": "Bereavement leave (AB 1949)",
   "topic": "bereavement_leave",
   "chars": 4343,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=GOV&sectionNum=12945.7.",
   "hash": "0dbc027732",
   "domain": "leave_benefits",
   "minEmp": 5,
   "appliesWhen": "employers with 5+ employees",
   "industries": [
    "all"
   ],
   "explainer": "Bereavement leave (AB 1949): at 5+ employees, up to 5 days of protected bereavement leave per death of a qualifying family member, taken within 3 months; may be unpaid but employees can use accrued paid time."
  },
  {
   "jur": "CA",
   "cit": "Cal. Gov. Code § 12950.1",
   "title": "Sexual harassment prevention training (SB 1343)",
   "topic": "harassment_training",
   "chars": 12391,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=GOV&sectionNum=12950.1.",
   "hash": "eff7cc2b96",
   "domain": "harassment_eeo",
   "minEmp": 5,
   "appliesWhen": "employers with 5+ employees",
   "industries": [
    "all"
   ],
   "explainer": "Mandatory sexual-harassment-prevention training (SB 1343) at 5+ employees: 2 hours for supervisors, 1 hour for all other employees, within 6 months of hire/promotion and every 2 years after. Seasonal/temporary workers must be trained within 30 days or 100 hours. Records must be kept — this maps directly to a CDO training requirement."
  },
  {
   "jur": "CA",
   "cit": "Cal. Gov. Code § 12952",
   "title": "Fair Chance Act — criminal history (ban-the-box)",
   "topic": "fair_chance",
   "chars": 6536,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=GOV&sectionNum=12952.",
   "hash": "5999803b9a",
   "domain": "harassment_eeo",
   "minEmp": 5,
   "appliesWhen": "employers with 5+ employees",
   "industries": [
    "all"
   ],
   "explainer": "Fair Chance Act (ban-the-box) at 5+ employees: no criminal-history questions until AFTER a conditional job offer; then an individualized assessment, written preliminary notice, 5 business days to respond, and a final written decision. A standardized hiring flow in CDO keeps this clean."
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 1030",
   "title": "Lactation accommodation — break time",
   "topic": "lactation",
   "chars": 633,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=1030.",
   "hash": "eef57a0ebb",
   "domain": "leave_benefits",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "Lactation break time: reasonable break time to express milk, running concurrently with paid breaks where possible (unpaid beyond them). One of three lactation sections — §1031 covers the space, §1034 the room specs."
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 1031",
   "title": "Lactation accommodation — location requirements",
   "topic": "lactation",
   "chars": 3590,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=1031.",
   "hash": "99cb7b0f13",
   "domain": "leave_benefits",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "Lactation space: a private location close to the work area that is NOT a bathroom. For field crews this is a real logistics question (job-site trailer, vehicle policy) worth a written procedure."
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 1034",
   "title": "Lactation room/space requirements (SB 142)",
   "topic": "lactation",
   "chars": 1132,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=1034.",
   "hash": "5666e50ee0",
   "domain": "leave_benefits",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "Lactation room requirements (SB 142): the space must be safe, clean, free of toxic materials, have a surface and seating, and access to electricity plus a sink and refrigeration close by. Denying adequate space is treated as a failure to provide a rest period (premium pay)."
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 1102.5",
   "title": "Whistleblower protection / anti-retaliation",
   "topic": "whistleblower",
   "chars": 4269,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=1102.5.",
   "hash": "3c399d55ea",
   "domain": "harassment_eeo",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "Whistleblower protection: employees can't be retaliated against for reporting suspected legal violations internally OR to any government agency — including Cal/OSHA complaints about safety. Penalties up to $10K per violation plus a 2024-strengthened presumption of retaliation for adverse action within 90 days of protected activity."
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 1182.12",
   "title": "State minimum wage",
   "topic": "minimum_wage",
   "chars": 10442,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=1182.12.",
   "hash": "ccef91dfe2",
   "domain": "wage_hour",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "The state minimum wage statute with its scheduled increases and the annual CPI adjustment mechanism. Reality check: many cities/counties set HIGHER local minimums, and prevailing-wage jobs pay far above this — but this is the legal floor every CA paycheck must clear."
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 1198.5",
   "title": "Employee right to inspect personnel records",
   "topic": "personnel_records",
   "chars": 8724,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=1198.5.",
   "hash": "bd31426735",
   "domain": "wage_hour",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "Personnel-file access: current and former employees may inspect/copy their personnel records; employer must comply within 30 days (max 50 requests/yr from former employees). Pairs with §226(b) pay-record access. CDO's document vault makes this trivially satisfiable."
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 1400",
   "title": "Cal/WARN Act — short title",
   "topic": "warn_act",
   "chars": 185,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=1400.",
   "hash": "55384cc812",
   "domain": "workforce_reduction",
   "minEmp": 75,
   "appliesWhen": "75+ employees",
   "industries": [
    "all"
   ],
   "explainer": "Cal/WARN's short-title section (post-AB 1601 renumbering) — it just names the act. The substance is in §1400.5 (definitions), §1401 (notice duty), and §1402 (liability), all captured as their own rows."
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 1400.5",
   "title": "Cal/WARN — definitions (covered establishment, mass layoff)",
   "topic": "warn_act",
   "chars": 2050,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=1400.5.",
   "hash": "518e697be3",
   "domain": "workforce_reduction",
   "minEmp": 75,
   "appliesWhen": "75+ employees",
   "industries": [
    "all"
   ],
   "explainer": "Cal/WARN definitions: 'covered establishment' = 75+ employees (incl. part-time, 6 of last 12 months); 'mass layoff' = 50+ employees in 30 days; also defines relocation and termination. Much broader than federal WARN (no 1/3-of-workforce threshold)."
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 1401",
   "title": "Cal/WARN — 60-day written notice before mass layoff/closure",
   "topic": "warn_act",
   "chars": 2981,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=1401.",
   "hash": "c6d530f9ab",
   "domain": "workforce_reduction",
   "minEmp": 75,
   "appliesWhen": "75+ employees",
   "industries": [
    "all"
   ],
   "explainer": "Cal/WARN's operative duty: 60 days' WRITTEN notice to affected employees, the EDD, the local workforce board, and local officials before a mass layoff, relocation, or plant closure at a covered establishment. Seasonal construction slowdowns have caused real Cal/WARN litigation — worth legal review before any large crew reduction."
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 1402",
   "title": "Cal/WARN — employer liability for failure to give notice",
   "topic": "warn_act",
   "chars": 1647,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=1402.",
   "hash": "9caf2a1286",
   "domain": "workforce_reduction",
   "minEmp": 75,
   "appliesWhen": "75+ employees",
   "industries": [
    "all"
   ],
   "explainer": "Cal/WARN liability: skip the notice and the employer owes each employee up to 60 days of back pay and benefits, plus civil penalties of $500/day. The cost of non-compliance usually dwarfs the cost of simply giving notice."
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 1771",
   "title": "Prevailing wages required on public works",
   "topic": "prevailing_wage",
   "chars": 668,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=1771.",
   "hash": "ce5b2b2534",
   "domain": "prevailing_wage",
   "minEmp": 1,
   "appliesWhen": "public works projects",
   "industries": [
    "all"
   ],
   "explainer": "Prevailing wage: on public works projects over $1,000, workers must be paid the DIR-determined prevailing rate for their craft and county — typically far above market wage. This is the trigger statute; rates come from DIR determinations updated twice a year."
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 1775",
   "title": "Prevailing wage — penalties for underpayment",
   "topic": "prevailing_wage",
   "chars": 5080,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=1775.",
   "hash": "49a1d4013c",
   "domain": "prevailing_wage",
   "minEmp": 1,
   "appliesWhen": "public works projects",
   "industries": [
    "all"
   ],
   "explainer": "Prevailing-wage penalties: up to $200 PER WORKER PER DAY of underpayment, plus back wages — and the prime contractor is liable for subs' violations. Certified payroll (eCPR) is how DIR checks. This is why the engine needs a jobs.is_public_works flag."
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 1777.5",
   "title": "Apprenticeship requirements on public works",
   "topic": "prevailing_wage",
   "chars": 13298,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=1777.5.",
   "hash": "25648626f0",
   "domain": "prevailing_wage",
   "minEmp": 1,
   "appliesWhen": "public works projects ≥ $30k",
   "industries": [
    "all"
   ],
   "explainer": "Apprenticeship on public works: contracts ≥ $30K require employing registered apprentices at a 1:5 apprentice-to-journeyman hours ratio, contributing to the apprenticeship fund, and requesting dispatch from local programs. Frequently missed by contractors new to public work."
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 201",
   "title": "Final pay on discharge — wages due immediately",
   "topic": "final_pay",
   "chars": 4560,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=201.",
   "hash": "31f5046e12",
   "domain": "wage_hour",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "Final pay on termination: ALL earned wages — including accrued, unused vacation — are due IMMEDIATELY at the moment of discharge. Not end of week, not next payroll. Immediately."
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 202",
   "title": "Final pay on resignation — within 72 hours (immediately if 72h notice)",
   "topic": "final_pay",
   "chars": 4748,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=202.",
   "hash": "9982bf5285",
   "domain": "wage_hour",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "Final pay on resignation: due within 72 hours of quitting — or immediately if the employee gave at least 72 hours' notice."
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 203",
   "title": "Waiting-time penalty — up to 30 days' wages for late final pay",
   "topic": "final_pay",
   "chars": 975,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=203.",
   "hash": "50cefce901",
   "domain": "wage_hour",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "The teeth behind §§201/202: willfully late final pay accrues a 'waiting-time penalty' of one full day of wages per day late, up to 30 days. A $240/day worker paid 30 days late costs $7,200 in penalty alone."
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 226",
   "title": "Itemized wage statements — required pay-stub line items",
   "topic": "wage_statements",
   "chars": 9461,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=226.",
   "hash": "6acd2ad4d4",
   "domain": "wage_hour",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "Itemized wage statements: every pay stub must show 9 things — gross wages, total hours, piece rates if any, all deductions, net wages, pay-period dates, employee name + last 4 of SSN, employer's full name/address, and all hourly rates with hours at each. Violations carry per-employee penalties and are a favorite of PAGA lawsuits."
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 230",
   "title": "Jury, witness & victim leave; protected time off",
   "topic": "civic_leave",
   "chars": 11813,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=230.",
   "hash": "5bcc29e845",
   "domain": "leave_benefits",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "Protected civic/victim time off: jury duty, court appearances as a crime victim, and time off + reasonable accommodations for victims of domestic violence, sexual assault, or stalking. No firing or discrimination for taking it; some pieces apply at 25+ employees."
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 230.8",
   "title": "Time off for a child's school activities",
   "topic": "civic_leave",
   "chars": 4510,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=230.8.",
   "hash": "39f69ccda6",
   "domain": "leave_benefits",
   "minEmp": 25,
   "appliesWhen": "employers with 25+ employees",
   "industries": [
    "all"
   ],
   "explainer": "School-activities leave at 25+ employees: up to 40 hours/year (max 8/month) of protected time off for a parent/guardian to participate in a child's school or daycare activities, using existing vacation/PTO."
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 233",
   "title": "Kin care — use of accrued sick leave for family",
   "topic": "paid_sick_leave",
   "chars": 2997,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=233.",
   "hash": "2adb7c3797",
   "domain": "leave_benefits",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "'Kin care': employees may use up to half their annual sick-leave accrual to care for a sick family member (broadly defined). An employer can't discipline someone for using sick leave this way."
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 246",
   "title": "Paid sick leave — accrual, use & rate (HWHFA)",
   "topic": "paid_sick_leave",
   "chars": 11928,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=246.",
   "hash": "4e7a90406f",
   "domain": "leave_benefits",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "California paid sick leave (HWHFA): accrual of at least 1 hour per 30 worked (or front-load 40 hours/5 days), use after 90 days, carryover with caps, no payout at separation required, and pay-stub disclosure of the balance. Applies to virtually every employee including part-time and seasonal crews."
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 2775",
   "title": "Independent-contractor ABC test (AB 5 / AB 2257)",
   "topic": "ab5",
   "chars": 2112,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=2775.",
   "hash": "d539cd9109",
   "domain": "worker_classification",
   "minEmp": 1,
   "appliesWhen": "engaging independent contractors",
   "industries": [
    "all"
   ],
   "explainer": "AB 5's ABC test, codified: a worker is an EMPLOYEE unless the hirer proves all three — (A) free from control, (B) work outside the hiring entity's usual business, and (C) an independently established trade. Prong B makes a 1099 'roofer' working for a roofing company nearly impossible; subcontractors must hold their own CSLB license (B&P §2750.5 overlay) to be legitimate."
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 2802",
   "title": "Reimbursement of necessary business expenses",
   "topic": "expense_reimbursement",
   "chars": 1580,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=2802.",
   "hash": "c5d5a51113",
   "domain": "wage_hour",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "Expense reimbursement: employers must reimburse ALL necessary business expenses — personal phone used for work, mileage between sites, required tools above the Wage Order allowance. Unreimbursed-expense class actions are common; a clear reimbursement policy is the defense."
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 2810.5",
   "title": "Wage Theft Prevention Act — written pay notice to employees at hire",
   "topic": "wage_notice",
   "chars": 6883,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=2810.5.",
   "hash": "b7491de653",
   "domain": "wage_hour",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "Wage Theft Prevention Act notice: at hire, every non-exempt employee must receive a WRITTEN notice stating pay rate(s), overtime rates, pay day, employer's legal name/addresses, workers' comp carrier, and paid-sick-leave rights — plus written notice within 7 days of any change. The DLSE publishes a template form."
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 3700",
   "title": "Workers' compensation insurance — required coverage",
   "topic": "workers_comp",
   "chars": 1773,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=3700.",
   "hash": "2e47081204",
   "domain": "licensing_insurance",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "Workers' compensation insurance is MANDATORY for every CA employer with even one employee. Operating uninsured is a criminal offense and triggers stop-work orders + penalties; for contractors it also voids the CSLB license. The compliance engine should treat a lapsed comp policy as a hard red flag."
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 432.3",
   "title": "Pay scale disclosure / pay transparency",
   "topic": "pay_transparency",
   "chars": 4909,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=432.3.",
   "hash": "79a86fd259",
   "domain": "wage_hour",
   "minEmp": 15,
   "appliesWhen": "pay scale in job postings: 15+ employees",
   "industries": [
    "all"
   ],
   "explainer": "Pay transparency: employers may not ask applicants for salary history; must provide a pay scale on request; and at 15+ employees must INCLUDE the pay scale in every job posting. Civil penalties per violation."
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 510",
   "title": "Overtime — daily/weekly rates (1.5× after 8h/day & 40h/week, 2× after 12h)",
   "topic": "overtime",
   "chars": 1817,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=510.",
   "hash": "d7d15904dc",
   "domain": "wage_hour",
   "minEmp": 1,
   "appliesWhen": "non-exempt employees",
   "industries": [
    "all"
   ],
   "explainer": "California daily overtime — stricter than federal: 1.5× after 8 hours in a DAY or 40 in a week and for the first 8 hours on the 7th consecutive day; 2× after 12 hours in a day or after 8 on the 7th day. Note: crews under a valid collective bargaining agreement or Wage Order 16 alternative workweek may have different schedules."
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 512",
   "title": "Meal periods — 30-min meal by the 5th hour; second meal by the 10th",
   "topic": "meal_rest",
   "chars": 4960,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=512.",
   "hash": "69b8693e3b",
   "domain": "wage_hour",
   "minEmp": 1,
   "appliesWhen": "non-exempt employees; shifts over 5 hours",
   "industries": [
    "all"
   ],
   "explainer": "Meal periods: a 30-minute unpaid, duty-free meal before the END of the 5th hour of work, and a second before the end of the 10th. Miss one and the employer owes a premium hour of pay. For construction crews, Wage Order 16 adds the on-site specifics and CBA exceptions."
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 551",
   "title": "Day of rest — one day's rest in seven",
   "topic": "day_of_rest",
   "chars": 137,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=551.",
   "hash": "d5be4fd03e",
   "domain": "wage_hour",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "One sentence of law: every worker is entitled to one day's rest in seven. The operative prohibition is §552 (next row). Per Mendoza v. Nordstrom, measured by the workweek, and employees may voluntarily choose to work 7 — but the employer can't cause it."
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 552",
   "title": "Day of rest — employer may not cause work more than 6 days in 7",
   "topic": "day_of_rest",
   "chars": 122,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=552.",
   "hash": "8005f903eb",
   "domain": "wage_hour",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "The day-of-rest prohibition with teeth: no employer may CAUSE employees to work more than 6 days in 7 (workweek basis). Exceptions exist for emergencies and for weeks where total hours don't exceed 30 (no day over 6). Schedule-building in CDO should warn on 7-day patterns."
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 6401.9",
   "title": "Workplace Violence Prevention Plan (SB 553)",
   "topic": "workplace_violence",
   "chars": 15891,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=6401.9.",
   "hash": "d245a3597f",
   "domain": "harassment_eeo",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "Workplace Violence Prevention Plan (SB 553, eff. July 2024): nearly every CA employer must have a written WVPP — violence hazard assessment, incident log, response procedures, and annual training. New enough that many contractors don't have one; an easy first compliance win for CDO to flag."
  },
  {
   "jur": "CA",
   "cit": "Cal. Lab. Code § 980",
   "title": "Social media privacy — no access to personal accounts",
   "topic": "social_media",
   "chars": 1739,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=LAB&sectionNum=980.",
   "hash": "fd698cd850",
   "domain": "privacy_conduct",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "Social-media privacy: employers can't demand usernames/passwords for personal accounts or require an employee to access them in the employer's presence. Keep it out of hiring and investigations."
  },
  {
   "jur": "CA",
   "cit": "Cal. Mil. & Vet. Code § 394",
   "title": "Military leave & protection from discrimination (CA)",
   "topic": "military_leave",
   "chars": 5161,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=MVC&sectionNum=394.",
   "hash": "57025932cb",
   "domain": "leave_benefits",
   "minEmp": 1,
   "appliesWhen": "employees in military service",
   "industries": [
    "all"
   ],
   "explainer": "California's military-leave protection: no discrimination or discharge because of National Guard/reserve membership or service, with reinstatement rights. The federal counterpart (USERRA, 20 CFR 1002) applies in parallel — comply with both."
  },
  {
   "jur": "CA",
   "cit": "Cal. UIC § 2601 (SDI — EDD)",
   "title": "EDD) — State Disability Insurance — program overview (DI + PFL umbrella)",
   "topic": "sdi",
   "chars": 2498,
   "url": "https://edd.ca.gov/en/disability/",
   "hash": "726d55842b",
   "domain": "leave_benefits",
   "minEmp": 1,
   "appliesWhen": "employee unable to work due to non-work illness/injury/pregnancy",
   "industries": [
    "all"
   ],
   "explainer": "State Disability Insurance: the umbrella program (DI + PFL) paying partial wages when a worker can't work due to a NON-work illness, injury, or pregnancy (work injuries are workers' comp instead). Employee-funded via payroll withholding; employer duties are notice/poster and payroll deduction mechanics."
  },
  {
   "jur": "CA",
   "cit": "Cal. UIC § 3301 (PFL — EDD)",
   "title": "EDD) — Paid Family Leave — up to 8 weeks wage replacement (EDD program)",
   "topic": "pfl",
   "chars": 3194,
   "url": "https://edd.ca.gov/en/disability/paid-family-leave/",
   "hash": "0eab897cb2",
   "domain": "leave_benefits",
   "minEmp": 1,
   "appliesWhen": "employee on leave to care for family / bond with new child",
   "industries": [
    "all"
   ],
   "explainer": "Paid Family Leave: a state WAGE-REPLACEMENT benefit (not job protection) paying workers up to 8 weeks at ~70–90% of wages to bond with a new child or care for a seriously ill family member. Funded entirely by employee SDI payroll deductions — costs the employer nothing. Job protection comes separately from CFRA. Employers must display/provide the EDD pamphlets."
  },
  {
   "jur": "CA",
   "cit": "Cal. Veh. Code § 23123.5",
   "title": "Handheld phone / texting while driving prohibited",
   "topic": "distracted_driving",
   "chars": 2042,
   "url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=VEH&sectionNum=23123.5.",
   "hash": "c979aaa7ef",
   "domain": "privacy_conduct",
   "minEmp": 1,
   "appliesWhen": "employees who drive for work",
   "industries": [
    "all"
   ],
   "explainer": "Hands-free driving: no holding a phone while driving — voice/single-tap mounted use only. Matters because employer liability attaches when crews drive between jobs on the clock; a written distracted-driving policy is the standard control."
  },
  {
   "jur": "CA",
   "cit": "EDD — DI benefit amounts",
   "title": "DI benefit amounts — DI weekly benefit amounts — wage-replacement % and maximums (updated annually)",
   "topic": "sdi",
   "chars": 6425,
   "url": "https://edd.ca.gov/en/disability/Calculating_DI_Benefit_Payment_Amounts/",
   "hash": "41d3e04e18",
   "domain": "leave_benefits",
   "minEmp": 1,
   "appliesWhen": "employee unable to work due to non-work illness/injury/pregnancy",
   "industries": [
    "all"
   ],
   "explainer": "The current Disability Insurance benefit math from EDD: ~70–90% wage replacement up to the annual cap, for up to 52 weeks. Updated annually — tracked by the hash watcher like the PFL amounts row."
  },
  {
   "jur": "CA",
   "cit": "EDD — PFL benefit amounts",
   "title": "PFL benefit amounts — PFL weekly benefit amounts — wage-replacement % and maximums (updated annually)",
   "topic": "pfl",
   "chars": 6590,
   "url": "https://edd.ca.gov/en/disability/Calculating_PFL_Benefit_Payment_Amounts/",
   "hash": "87404e599c",
   "domain": "leave_benefits",
   "minEmp": 1,
   "appliesWhen": "employee on leave to care for family / bond with new child",
   "industries": [
    "all"
   ],
   "explainer": "The current PFL benefit math from EDD: weekly benefit ≈ 70–90% of the worker's highest quarter (higher % for lower earners, per SB 951), up to the annual maximum weekly benefit. These numbers change EVERY JANUARY — this row exists so the hash watcher catches the annual update automatically."
  },
  {
   "jur": "CA",
   "cit": "EDD — SDI/PFL contribution rates",
   "title": "SDI/PFL contribution rates — SDI/PFL employee contribution rate & payroll-tax rates (updated annually)",
   "topic": "sdi",
   "chars": 11089,
   "url": "https://edd.ca.gov/en/payroll_taxes/rates_and_withholding/",
   "hash": "be30bb66da",
   "domain": "leave_benefits",
   "minEmp": 1,
   "appliesWhen": "all CA employers — employee payroll withholding",
   "industries": [
    "all"
   ],
   "explainer": "The employer-facing payroll mechanics: the current-year SDI withholding rate (the wage-base cap was removed in 2024 — the rate now applies to ALL wages), plus UI/ETT rates. This is what payroll must actually deduct; it changes every January 1."
  },
  {
   "jur": "CA",
   "cit": "IWC Wage Order 16-2001",
   "title": "on-site construction: wages, hours & working conditions",
   "topic": "wage_order",
   "chars": 43168,
   "url": "https://www.dir.ca.gov/iwc/IWCArticle16.pdf",
   "hash": "d7dcd0e3fd",
   "domain": "wage_hour",
   "minEmp": 1,
   "appliesWhen": "on-site construction occupations (incl. roofing crews)",
   "industries": [
    "construction"
   ],
   "explainer": "The Industrial Welfare Commission's wage order for ON-SITE CONSTRUCTION occupations — the industry-specific layer on top of the Labor Code that directly governs roofing crews: meal/rest period rules as applied on construction sites, daily/weekly overtime, alternative workweek schedules, reporting-time pay (half-day pay if sent home early), tool requirements, and record-keeping. Published only as a PDF (rev. 11/2025); we extract and watch the full text. Where a CBA meets the statutory tests, several provisions can be superseded."
  },
  {
   "jur": "Federal",
   "cit": "20 CFR § 1002.18",
   "title": "USERRA — protected status & anti-discrimination",
   "topic": "military_leave",
   "chars": 397,
   "url": "https://www.ecfr.gov/current/title-20/section-1002.18",
   "hash": "12ad12e707",
   "domain": "leave_benefits",
   "minEmp": 1,
   "appliesWhen": "employees in uniformed service",
   "industries": [
    "all"
   ],
   "explainer": "USERRA's anti-discrimination core: employers may not deny hiring, reemployment, promotion, or any benefit because of military service or obligations — and may not retaliate. There is no small-employer exception."
  },
  {
   "jur": "Federal",
   "cit": "20 CFR § 1002.180",
   "title": "USERRA — right to reemployment after uniformed service",
   "topic": "military_leave",
   "chars": 287,
   "url": "https://www.ecfr.gov/current/title-20/section-1002.180",
   "hash": "0861ba1f32",
   "domain": "leave_benefits",
   "minEmp": 1,
   "appliesWhen": "employees in uniformed service",
   "industries": [
    "all"
   ],
   "explainer": "USERRA reemployment right: a returning service member is entitled to prompt reemployment in the position they would have attained had they never left (the 'escalator' principle), with seniority and benefits, if they gave notice, served under 5 cumulative years, and returned/applied within the deadlines. Pairs with CA Mil. & Vet. Code §394."
  },
  {
   "jur": "Federal",
   "cit": "20 CFR § 1002.5",
   "title": "USERRA — definitions",
   "topic": "military_leave",
   "chars": 7792,
   "url": "https://www.ecfr.gov/current/title-20/section-1002.5",
   "hash": "41860ad615",
   "domain": "leave_benefits",
   "minEmp": 1,
   "appliesWhen": "employees in uniformed service",
   "industries": [
    "all"
   ],
   "explainer": "USERRA definitions: who is protected (uniformed service members, reservists, National Guard), what counts as 'service in the uniformed services', and key terms (seniority, escalator position) used by the reemployment rules. Applies to ALL employers regardless of size."
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1604.11",
   "title": "Title VII — sexual harassment guidelines",
   "topic": "title_vii",
   "chars": 3822,
   "url": "https://www.ecfr.gov/current/title-29/section-1604.11",
   "hash": "8ae6c21791",
   "domain": "harassment_eeo",
   "minEmp": 15,
   "appliesWhen": "15+ employees",
   "industries": [
    "all"
   ],
   "explainer": "The EEOC's sexual-harassment guidelines under Title VII: defines quid pro quo and hostile-environment harassment, employer liability for supervisors/coworkers/non-employees, and the duty to prevent and promptly correct. CA layering: FEHA + mandatory SB 1343 training."
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1630.2",
   "title": "ADA — definitions (disability, reasonable accommodation, undue hardship)",
   "topic": "ada",
   "chars": 23794,
   "url": "https://www.ecfr.gov/current/title-29/section-1630.2",
   "hash": "581cb59c83",
   "domain": "harassment_eeo",
   "minEmp": 15,
   "appliesWhen": "15+ employees",
   "industries": [
    "all"
   ],
   "explainer": "ADA definitions (15+ employees): what counts as a disability, what 'reasonable accommodation' and 'undue hardship' mean, and 'direct threat'. These definitions drive every accommodation conversation — including return-to-work after injuries, which roofing sees often."
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1630.9",
   "title": "ADA — reasonable accommodation & not making accommodation",
   "topic": "ada",
   "chars": 1962,
   "url": "https://www.ecfr.gov/current/title-29/section-1630.9",
   "hash": "9fe025a775",
   "domain": "harassment_eeo",
   "minEmp": 15,
   "appliesWhen": "15+ employees",
   "industries": [
    "all"
   ],
   "explainer": "The ADA's operative duty: employers must provide reasonable accommodation to qualified individuals with disabilities unless it causes undue hardship — and may not deny jobs to avoid accommodating. The interactive process with the employee is the practical requirement here. CA's FEHA mirrors this at 5+ employees."
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1910.1200",
   "title": "Hazard communication",
   "topic": "hazcom",
   "chars": 305785,
   "url": "https://www.ecfr.gov/current/title-29/section-1910.1200",
   "hash": "a2e12658d3",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "The FULL federal Hazard Communication standard (construction §1926.59 just points here): written program, chemical inventory, GHS-compliant labels, Safety Data Sheets accessible on site, and effective worker training — in a language workers understand — on every hazardous chemical. This row carries the complete 300K-char text so the actual obligations are in our database, not just a pointer."
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1910.134",
   "title": "Respiratory protection",
   "topic": "respiratory_hazmat",
   "chars": 122860,
   "url": "https://www.ecfr.gov/current/title-29/section-1910.134",
   "hash": "d7116cdf4d",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "The FULL federal Respiratory Protection standard (construction §1926.103 just points here): written respirator program with a designated administrator, medical evaluation BEFORE first use, annual fit testing, seal checks, maintenance/storage rules, and specific procedures for voluntary N95 use (Appendix D). Any asbestos/silica/lead task that puts a respirator on a face makes this entire program mandatory."
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.100",
   "title": "Head protection",
   "topic": "ppe",
   "chars": 1643,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.100",
   "hash": "1be8fc8ac3",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "construction"
   ],
   "explainer": "Federal hard-hat rule: helmets required where there is possible danger of head injury from impact, falling/flying objects, or electrical shock/burns. Must meet ANSI Z89.1."
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.101",
   "title": "Hearing protection",
   "topic": "ppe",
   "chars": 410,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.101",
   "hash": "b14d695590",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "construction"
   ],
   "explainer": "Federal hearing protection: where noise can't be reduced below the Table D-2 levels in §1926.52, ear protective devices must be provided and used; plain cotton is explicitly not acceptable. Relevant around saws, compressors, and tear-off equipment."
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.102",
   "title": "Eye and face protection",
   "topic": "ppe",
   "chars": 4561,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.102",
   "hash": "e0ddaaba62",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "construction"
   ],
   "explainer": "Federal eye/face protection: ANSI Z87.1 protection required for flying objects, glare, liquids, and radiant energy — with a selection table by operation (chipping, cutting, welding shades) and prescription-eyewear rules."
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.103",
   "title": "Respiratory protection",
   "topic": "respiratory_hazmat",
   "chars": 204,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.103",
   "hash": "3a7acfa9a5",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": "respirator use required by another standard",
   "industries": [
    "construction"
   ],
   "explainer": "A one-line cross-reference: federal construction respiratory protection IS general-industry §1910.134. We hold the full 1910.134 text as its own row — review that one for the substance; this row exists so the construction-side citation resolves."
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.1051",
   "title": "General requirements",
   "topic": "ladders",
   "chars": 1448,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.1051",
   "hash": "ed2706669f",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": "ladder/stairway use on site",
   "industries": [
    "construction"
   ],
   "explainer": "Federal stairway/ladder access rule: a stairway or ladder is REQUIRED at any access point with a 19-inch or greater elevation break — i.e., getting on a roof requires a compliant ladder, and workers must be trained on ladder hazards (§1060)."
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.1053",
   "title": "Ladders",
   "topic": "ladders",
   "chars": 16991,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.1053",
   "hash": "00cc6cef0a",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": "ladder use on site",
   "industries": [
    "construction"
   ],
   "explainer": "Federal ladder specifications and use: side rails extending 3 ft above the landing, secured against displacement, 4:1 setup angle, no carrying loads that cause loss of balance, defective ladders tagged out. Ladder misuse is among the most-cited violations in roofing."
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.1101",
   "title": "Asbestos",
   "topic": "respiratory_hazmat",
   "chars": 233383,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.1101",
   "hash": "8cb2773b4f",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": "disturbing asbestos-containing materials (common in tear-off)",
   "industries": [
    "construction"
   ],
   "explainer": "Federal construction asbestos standard — the longest rule in our catalog (233K chars) because it's effectively a complete program: work classes I–IV, PEL 0.1 f/cc, presumed asbestos in pre-1981 buildings, competent persons, regulated areas, wet methods, decontamination, medical surveillance, and disposal. Roofing felts/mastics are explicitly addressed (Class II work)."
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.1153",
   "title": "Respirable crystalline silica",
   "topic": "respiratory_hazmat",
   "chars": 82422,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.1153",
   "hash": "e3452174b6",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": "cutting/grinding/disturbing silica-containing materials",
   "industries": [
    "construction"
   ],
   "explainer": "Federal respirable crystalline silica in construction: PEL 50 µg/m³, action level 25 µg/m³. Table 1 lists 18 task categories (masonry saws, grinders, drills) with specified controls — follow Table 1 exactly and you're deemed compliant; otherwise monitor air. Requires a written exposure control plan and a designated competent person. Tile and fiber-cement work is where roofers hit this."
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.250",
   "title": "General requirements for storage",
   "topic": "materials_handling",
   "chars": 3585,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.250",
   "hash": "261bd9e6d9",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "construction"
   ],
   "explainer": "Federal material-storage rules: stored materials must not create hazards — secured against sliding/collapse, aisles kept clear, and (critically for roofing) materials stored on roofs must be stacked/secured so they can't slide or blow off, with weight limits respected."
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.252",
   "title": "Disposal of waste materials",
   "topic": "materials_handling",
   "chars": 1167,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.252",
   "hash": "1783c9c3cb",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "construction"
   ],
   "explainer": "Federal waste-disposal rule for demolition/tear-off: debris dropped more than 20 ft must go through an enclosed chute; drop areas must be barricaded and signed; debris can't accumulate into a hazard. This is THE federal citation for how tear-off debris legally leaves a roof."
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.451",
   "title": "General requirements",
   "topic": "scaffolds",
   "chars": 42764,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.451",
   "hash": "2e5368d536",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": "scaffold use on site",
   "industries": [
    "construction"
   ],
   "explainer": "Federal scaffold general requirements: capacity (4:1 safety factor), platform construction, max gaps, safe access (no climbing cross-braces), fall protection at 10 ft on scaffolds, and competent-person inspection before each shift. Applies whenever staging or supported scaffolds are used for roof access or edge work."
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.500",
   "title": "Scope, application, and definitions applicable to this subpart",
   "topic": "fall_protection",
   "chars": 12826,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.500",
   "hash": "7433366d63",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "construction"
   ],
   "explainer": "Scope and definitions for federal Subpart M (fall protection): defines the terms every other fall rule uses — unprotected side/edge, low-slope vs steep roof, leading edge, anchorage, competent person. Included so the defined terms behind §§501–503 are part of the record."
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.501",
   "title": "Duty to have fall protection",
   "topic": "fall_protection",
   "chars": 10036,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.501",
   "hash": "1e1e212f48",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "construction"
   ],
   "explainer": "The federal duty to provide fall protection: 6 ft above a lower level in construction. For roofing specifically — low-slope roofs may use guardrails, nets, PFAS, or a warning-line + safety-monitor combo ((b)(10)); steep roofs require guardrails with toeboards, nets, or PFAS. This is the federal floor; CA's §1730/1731 are stricter and control in California."
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.502",
   "title": "Fall protection systems criteria and practices",
   "topic": "fall_protection",
   "chars": 30436,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.502",
   "hash": "4b08f53e33",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "construction"
   ],
   "explainer": "The engineering criteria behind every federal fall-protection system: guardrail heights and strength (42\" ±3\", 200 lbs), personal fall arrest specs (5,000-lb anchors, max arresting forces, free-fall limits), warning-line and safety-monitor rules, and covers for roof openings. If §501 says 'protect', §502 says exactly what compliant protection looks like."
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.503",
   "title": "Training requirements",
   "topic": "fall_protection",
   "chars": 3021,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.503",
   "hash": "edb416fbc7",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "construction"
   ],
   "explainer": "Federal fall-protection TRAINING requirements: every worker exposed to fall hazards must be trained by a competent person to recognize fall hazards and use the systems on site; the employer must keep a WRITTEN certification (name, date, trainer signature) and retrain when conditions, equipment, or worker performance show the training didn't stick. This is the citation behind CDO's fall-protection training requirement."
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.55",
   "title": "Gases, vapors, fumes, dusts, and mists",
   "topic": "respiratory_hazmat",
   "chars": 27902,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.55",
   "hash": "304afd1f94",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "construction"
   ],
   "explainer": "Federal exposure limits for gases, vapors, fumes, dusts, and mists in construction: keep exposures under the Appendix A threshold limit values, prefer engineering/administrative controls, use respirators per §134 when controls aren't feasible. This is the catch-all air-contaminant rule behind fumes from kettles, adhesives, and dust."
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.59",
   "title": "Hazard communication",
   "topic": "hazcom",
   "chars": 199,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.59",
   "hash": "dd5d996398",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "construction"
   ],
   "explainer": "A one-line cross-reference: federal construction HazCom IS general-industry §1910.1200. We hold the full 1910.1200 text as its own row — review that one for the substance. In California the controlling standard is 8 CCR §5194."
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.62",
   "title": "Lead",
   "topic": "respiratory_hazmat",
   "chars": 149552,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.62",
   "hash": "9105c17a4b",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": "disturbing lead-containing materials/coatings",
   "industries": [
    "construction"
   ],
   "explainer": "Federal construction lead standard: PEL 50 µg/m³ (8-hr TWA), action level 30 µg/m³. Specific 'trigger tasks' (demolition of lead-painted surfaces, torch work) require interim protection — supplied-air or HEPA respirators, protective clothing, blood-lead testing — until the employer proves exposure is below limits. Old flashing and paints make this real on tear-offs."
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.95",
   "title": "Criteria for personal protective equipment",
   "topic": "ppe",
   "chars": 3137,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.95",
   "hash": "6a9f5b8dc0",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "construction"
   ],
   "explainer": "The federal umbrella PPE rule for construction: protective equipment for eyes, face, head, and extremities must be provided, used, and maintained wherever hazards are present — and the employer pays for required PPE. The body-part specifics live in §§96–102."
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 1926.96",
   "title": "Occupational foot protection",
   "topic": "ppe",
   "chars": 222,
   "url": "https://www.ecfr.gov/current/title-29/section-1926.96",
   "hash": "36b202703d",
   "domain": "safety",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "construction"
   ],
   "explainer": "Federal foot-protection rule: safety-toe footwear meeting the ANSI standard where foot injury hazards exist. Short section — the substance is the referenced ANSI/ASTM spec."
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 541.100",
   "title": "FLSA — executive exemption (white-collar test)",
   "topic": "flsa_exempt",
   "chars": 1425,
   "url": "https://www.ecfr.gov/current/title-29/section-541.100",
   "hash": "5af123acd3",
   "domain": "wage_hour",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "The FLSA executive exemption test — what it takes for a manager to be legally exempt from overtime: salary basis at the federal minimum threshold, primary duty of management, directing 2+ employees, and hire/fire authority or weight. Misclassifying foremen as exempt is a classic construction wage violation; CA's exemption test is stricter still."
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 778.107",
   "title": "FLSA — general overtime pay standard (1.5× after 40h/week)",
   "topic": "flsa_overtime",
   "chars": 1551,
   "url": "https://www.ecfr.gov/current/title-29/section-778.107",
   "hash": "053ea5b73f",
   "domain": "wage_hour",
   "minEmp": 1,
   "appliesWhen": null,
   "industries": [
    "all"
   ],
   "explainer": "The federal overtime baseline (FLSA): non-exempt employees get 1.5× their regular rate after 40 hours in a workweek. California adds daily overtime on top (LAB §510) — in CA you comply with BOTH, applying whichever rule pays more for a given hour."
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 825.100",
   "title": "FMLA — general / the Act in a nutshell",
   "topic": "fmla",
   "chars": 3232,
   "url": "https://www.ecfr.gov/current/title-29/section-825.100",
   "hash": "0e3e50a442",
   "domain": "leave_benefits",
   "minEmp": 50,
   "appliesWhen": "50+ employees within 75 miles",
   "industries": [
    "all"
   ],
   "explainer": "FMLA overview: covered employers (50+ employees) must give eligible workers up to 12 weeks of job-protected, unpaid leave per year for serious health conditions, new children, or qualifying military family needs — with group health benefits maintained and reinstatement to the same/equivalent job. Federal floor; CA's CFRA applies at just 5 employees."
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 825.112",
   "title": "FMLA — qualifying reasons for leave",
   "topic": "fmla",
   "chars": 1695,
   "url": "https://www.ecfr.gov/current/title-29/section-825.112",
   "hash": "6311166454",
   "domain": "leave_benefits",
   "minEmp": 50,
   "appliesWhen": "50+ employees within 75 miles",
   "industries": [
    "all"
   ],
   "explainer": "The qualifying reasons for FMLA leave, spelled out: birth/bonding, adoption/foster placement, the employee's own serious health condition, caring for a spouse/child/parent with one, and military exigencies/caregiving. Useful as the checklist for whether a leave request is FMLA-protected."
  },
  {
   "jur": "Federal",
   "cit": "29 CFR § 825.200",
   "title": "FMLA — amount of leave (12 workweeks)",
   "topic": "fmla",
   "chars": 7554,
   "url": "https://www.ecfr.gov/current/title-29/section-825.200",
   "hash": "e9545f9f9a",
   "domain": "leave_benefits",
   "minEmp": 50,
   "appliesWhen": "50+ employees within 75 miles",
   "industries": [
    "all"
   ],
   "explainer": "The FMLA amounts: 12 workweeks in a 12-month period (employer may choose the 12-month measuring method, e.g. rolling), and up to 26 weeks for military caregiver leave. Defines how intermittent leave counts against the entitlement."
  }
 ],
 "sources": [
  {
   "jur": "Federal",
   "name": "Federal OSHA — 29 CFR Part 1926 (Construction Safety & Health)",
   "kind": "api",
   "url": "https://www.ecfr.gov/current/title-29/part-1926",
   "scraped": "2026-06-10",
   "note": "Source of record for the federal floor. Heat has no specific 1926 standard yet (covered by OSH Act Gen. Duty Clause 5(a)(1); a federal heat rule was proposed in 2024 but is not in the CFR).",
   "n": 22
  },
  {
   "jur": "CA",
   "name": "Cal/OSHA — Title 8 (Construction & General Industry Safety Orders)",
   "kind": "scrape",
   "url": "https://www.dir.ca.gov/title8/",
   "scraped": "2026-06-10",
   "note": "California is stricter than the federal floor: it has a dedicated roofing article and a specific Heat Illness standard (§3395).",
   "n": 24
  },
  {
   "jur": "CA",
   "name": "California statutes — leginfo (Labor / Government / B&P Codes)",
   "kind": "scrape",
   "url": "https://leginfo.legislature.ca.gov/faces/codesTOCSelected.xhtml?tocCode=LAB",
   "scraped": "2026-06-10",
   "note": "Authoritative CA statute text from the Legislature, across codes. Backs the non-safety compliance domains (wage/hour, leave, harassment, licensing, prevailing wage).",
   "n": 43
  },
  {
   "jur": "Federal",
   "name": "Federal eCFR — 29 CFR (labor & employment)",
   "kind": "api",
   "url": "https://www.ecfr.gov/current/title-29",
   "scraped": "2026-06-10",
   "note": "eCFR API (no key). Federal employment floor: FMLA 825, FLSA 541/778, ADA 1630, Title VII 1604.",
   "n": 11
  },
  {
   "jur": "Federal",
   "name": "Federal Register — rules & proposed rules (API)",
   "kind": "api",
   "url": "https://www.federalregister.gov/developers/api/v1",
   "scraped": null,
   "note": "JSON, no auth. System of record for federal rule CHANGES; filter agency=OSHA/DOL/EEOC; de-dup by FR document number.",
   "n": 0
  },
  {
   "jur": "Federal",
   "name": "OSHA — News Releases",
   "kind": "rss",
   "url": "https://www.osha.gov/news/newsreleases.xml",
   "scraped": null,
   "note": "RSS feed for OSHA enforcement/guidance news.",
   "n": 0
  },
  {
   "jur": "Federal",
   "name": "US DOL Wage & Hour Division — news",
   "kind": "rss",
   "url": "https://www.dol.gov/agencies/whd/news",
   "scraped": null,
   "note": "FLSA/FMLA enforcement & guidance updates.",
   "n": 0
  },
  {
   "jur": "Federal",
   "name": "EEOC — Press Releases",
   "kind": "rss",
   "url": "https://www.eeoc.gov/newsroom/press-releases",
   "scraped": null,
   "note": "Title VII / ADA / EEO enforcement & guidance.",
   "n": 0
  },
  {
   "jur": "Federal",
   "name": "US DOL — FMLA",
   "kind": "scrape",
   "url": "https://www.dol.gov/agencies/whd/fmla",
   "scraped": null,
   "note": "FMLA guidance, fact sheets, posters.",
   "n": 0
  },
  {
   "jur": "Federal",
   "name": "Regulations.gov — dockets & comments (API)",
   "kind": "api",
   "url": "https://api.regulations.gov/v4",
   "scraped": null,
   "note": "Needs api.data.gov key (stored in .env). Proposed-rule dockets.",
   "n": 0
  },
  {
   "jur": "Federal",
   "name": "Congress.gov — federal statutes (API)",
   "kind": "api",
   "url": "https://api.congress.gov/v3",
   "scraped": null,
   "note": "Needs Congress key (stored in .env). Enacted/amended labor statutes.",
   "n": 0
  },
  {
   "jur": "CA",
   "name": "Cal/OSHA Standards Board — rulemaking",
   "kind": "scrape",
   "url": "https://www.dir.ca.gov/oshsb/oshsb.html",
   "scraped": null,
   "note": "Proposed/approved CA safety standards + hearing agendas (leading indicator of change).",
   "n": 0
  },
  {
   "jur": "CA",
   "name": "CA EDD — PFL & SDI (benefit amounts & rates)",
   "kind": "scrape",
   "url": "https://edd.ca.gov/en/disability/",
   "scraped": "2026-06-10",
   "note": "PFL / SDI program rules, benefit amounts & contribution rates (UIC sections leginfo won't serve cleanly).",
   "n": 5
  },
  {
   "jur": "CA",
   "name": "CA Civil Rights Department (CRD / DFEH)",
   "kind": "scrape",
   "url": "https://calcivilrights.ca.gov/news",
   "scraped": null,
   "note": "FEHA / CFRA / PDL regulations & guidance.",
   "n": 0
  },
  {
   "jur": "CA",
   "name": "CalChamber — HR Watchdog",
   "kind": "subscription",
   "url": "https://www.calchamber.com/hrwatchdog",
   "scraped": null,
   "note": "PAID feed — no scraping; secondary signal only.",
   "n": 0
  },
  {
   "jur": "CA",
   "name": "IWC Wage Orders (Wage Order 16 — construction)",
   "kind": "scrape",
   "url": "https://www.dir.ca.gov/iwc/WageOrderIndustries.htm",
   "scraped": "2026-06-10",
   "note": "Wage Order 16 governs on-site construction (meal/rest/OT for roofing). Scraped from the IWCArticle16.pdf via pdfplumber.",
   "n": 1
  },
  {
   "jur": "CA",
   "name": "CSLB — Contractors State License Board",
   "kind": "scrape",
   "url": "https://www.cslb.ca.gov",
   "scraped": null,
   "note": "C-39 roofing license + bond requirements & disciplinary rule changes.",
   "n": 0
  },
  {
   "jur": "Industry",
   "name": "NRCA — National Roofing Contractors Assoc.",
   "kind": "scrape",
   "url": "https://www.nrca.net",
   "scraped": null,
   "note": "ROOFING — newsletter + standards/best practices (our launch industry).",
   "n": 0
  },
  {
   "jur": "Industry",
   "name": "ABC — Associated Builders & Contractors",
   "kind": "scrape",
   "url": "https://www.abc.org",
   "scraped": null,
   "note": "Construction (general) — safety council updates.",
   "n": 0
  },
  {
   "jur": "Industry",
   "name": "PHCC — Plumbing-Heating-Cooling Contractors",
   "kind": "scrape",
   "url": "https://www.phccweb.org",
   "scraped": null,
   "note": "Plumbing — future industry (not active for roofing).",
   "n": 0
  },
  {
   "jur": "Industry",
   "name": "ACCA — Air Conditioning Contractors",
   "kind": "scrape",
   "url": "https://www.acca.org",
   "scraped": null,
   "note": "HVAC — future industry (not active for roofing).",
   "n": 0
  },
  {
   "jur": "Industry",
   "name": "IAPMO — Uniform Plumbing Code",
   "kind": "scrape",
   "url": "https://www.iapmo.org",
   "scraped": null,
   "note": "Plumbing — future industry (not active for roofing).",
   "n": 0
  }
 ],
 "topic": {
  "fall_protection": {
   "n": "Fall Protection",
   "c": "#ff6b6b"
  },
  "roofing_ops": {
   "n": "Roofing Ops",
   "c": "#f5b301"
  },
  "heat_illness": {
   "n": "Heat Illness",
   "c": "#f97316"
  },
  "respiratory_hazmat": {
   "n": "Respiratory / Hazmat",
   "c": "#a855f7"
  },
  "ppe": {
   "n": "PPE",
   "c": "#22d3ee"
  },
  "materials_handling": {
   "n": "Materials / Debris",
   "c": "#34d399"
  },
  "ladders": {
   "n": "Ladders",
   "c": "#60a5fa"
  },
  "scaffolds": {
   "n": "Scaffolds",
   "c": "#818cf8"
  },
  "hazcom": {
   "n": "HazCom",
   "c": "#fbbf24"
  },
  "safety_program": {
   "n": "IIPP / Safety Program",
   "c": "#14b8a6"
  },
  "lockout_tagout": {
   "n": "Lockout/Tagout",
   "c": "#f472b6"
  },
  "fire_safety": {
   "n": "Fire Safety",
   "c": "#fb7185"
  },
  "first_aid": {
   "n": "First Aid",
   "c": "#4ade80"
  },
  "confined_space": {
   "n": "Confined Space",
   "c": "#94a3b8"
  },
  "overtime": {
   "n": "Overtime",
   "c": "#2dd4bf"
  },
  "meal_rest": {
   "n": "Meal & Rest",
   "c": "#5eead4"
  },
  "wage_statements": {
   "n": "Wage Statements",
   "c": "#38bdf8"
  },
  "final_pay": {
   "n": "Final Pay",
   "c": "#a78bfa"
  },
  "minimum_wage": {
   "n": "Minimum Wage",
   "c": "#84cc16"
  },
  "wage_notice": {
   "n": "Wage Theft Notice",
   "c": "#f0abfc"
  },
  "paid_sick_leave": {
   "n": "Paid Sick Leave",
   "c": "#fcd34d"
  },
  "family_medical_leave": {
   "n": "Family/Medical Leave",
   "c": "#fca5a5"
  },
  "bereavement_leave": {
   "n": "Bereavement",
   "c": "#d8b4fe"
  },
  "civic_leave": {
   "n": "Jury/Civic Leave",
   "c": "#93c5fd"
  },
  "discrimination": {
   "n": "FEHA / Discrimination",
   "c": "#f9a8d4"
  },
  "harassment_training": {
   "n": "Harassment Training",
   "c": "#fdba74"
  },
  "workplace_violence": {
   "n": "Workplace Violence",
   "c": "#e879f9"
  },
  "workers_comp": {
   "n": "Workers' Comp",
   "c": "#67e8f9"
  },
  "contractor_license": {
   "n": "Contractor License",
   "c": "#facc15"
  },
  "prevailing_wage": {
   "n": "Prevailing Wage",
   "c": "#bef264"
  },
  "fmla": {
   "n": "FMLA (federal)",
   "c": "#f87171"
  },
  "flsa_overtime": {
   "n": "FLSA Overtime",
   "c": "#06b6d4"
  },
  "flsa_exempt": {
   "n": "FLSA Exemptions",
   "c": "#0ea5e9"
  },
  "ada": {
   "n": "ADA (federal)",
   "c": "#c084fc"
  },
  "title_vii": {
   "n": "Title VII",
   "c": "#ec4899"
  },
  "expense_reimbursement": {
   "n": "Expense Reimbursement",
   "c": "#34d399"
  },
  "day_of_rest": {
   "n": "Day of Rest",
   "c": "#a3e635"
  },
  "pay_transparency": {
   "n": "Pay Transparency",
   "c": "#fde047"
  },
  "personnel_records": {
   "n": "Personnel Records",
   "c": "#7dd3fc"
  },
  "lactation": {
   "n": "Lactation",
   "c": "#fbcfe8"
  },
  "military_leave": {
   "n": "Military Leave",
   "c": "#86efac"
  },
  "fair_chance": {
   "n": "Fair Chance / Ban-Box",
   "c": "#fca5a5"
  },
  "whistleblower": {
   "n": "Whistleblower",
   "c": "#fde68a"
  },
  "ab5": {
   "n": "Worker Classification",
   "c": "#c4b5fd"
  },
  "calsavers": {
   "n": "CalSavers Retirement",
   "c": "#6ee7b7"
  },
  "social_media": {
   "n": "Social Media Privacy",
   "c": "#93c5fd"
  },
  "trade_secrets": {
   "n": "Trade Secrets",
   "c": "#d4d4d8"
  },
  "distracted_driving": {
   "n": "Distracted Driving",
   "c": "#fdba74"
  },
  "warn_act": {
   "n": "WARN Act (layoffs)",
   "c": "#f9a8d4"
  },
  "pfl": {
   "n": "Paid Family Leave (PFL)",
   "c": "#fda4af"
  },
  "sdi": {
   "n": "Disability Ins. (SDI)",
   "c": "#a5b4fc"
  },
  "wage_order": {
   "n": "Wage Order 16 (constr.)",
   "c": "#fbbf24"
  }
 },
 "crit30": [
  {
   "n": "01",
   "p": "IIPP — Injury & Illness Prevention Program",
   "cit": "8 CCR § 3203",
   "st": "ok",
   "our": "8 CCR § 3203 ✓"
  },
  {
   "n": "02",
   "p": "Heat Illness Prevention",
   "cit": "8 CCR § 3395",
   "st": "ok",
   "our": "8 CCR § 3395 ✓"
  },
  {
   "n": "03",
   "p": "Fall Protection in Construction",
   "cit": "8 CCR § 1670",
   "st": "ok",
   "our": "8 CCR § 1670 ✓"
  },
  {
   "n": "04",
   "p": "Respiratory Protection",
   "cit": "8 CCR § 5144",
   "st": "ok",
   "our": "8 CCR § 5144 ✓"
  },
  {
   "n": "05",
   "p": "Confined Space Entry (construction)",
   "cit": "8 CCR § 1950",
   "st": "ok",
   "our": "8 CCR § 1950 ✓"
  },
  {
   "n": "06",
   "p": "Hazard Communication / HazCom",
   "cit": "8 CCR § 5194",
   "st": "ok",
   "our": "8 CCR § 5194 ✓"
  },
  {
   "n": "07",
   "p": "PPE — Personal Protective Equipment",
   "cit": "8 CCR § 3380",
   "st": "ok",
   "our": "8 CCR § 3380 ✓"
  },
  {
   "n": "08",
   "p": "Lockout / Tagout",
   "cit": "8 CCR § 3314",
   "st": "ok",
   "our": "8 CCR § 3314 ✓"
  },
  {
   "n": "09",
   "p": "Fire Safety",
   "cit": "8 CCR § 3221",
   "st": "ok",
   "our": "8 CCR § 3221 ✓"
  },
  {
   "n": "10",
   "p": "First Aid + CPR readiness",
   "cit": "8 CCR § 3400",
   "st": "ok",
   "our": "8 CCR § 3400 ✓"
  }
 ],
 "tables": {
  "sources": 22,
  "documents": 0,
  "leave_rules": 0,
  "regulations": 106,
  "prod_catalog": 26
 },
 "generatedAt": "2026-06-10 11:43",
 "counts": {
  "total": 106,
  "ca": 73,
  "federal": 33,
  "topics": 52,
  "chars": 1848987,
  "crit30_ok": 10,
  "crit30_total": 10
 },
 "domains": [
  "benefits_retirement",
  "harassment_eeo",
  "leave_benefits",
  "licensing_insurance",
  "prevailing_wage",
  "privacy_conduct",
  "safety",
  "wage_hour",
  "worker_classification",
  "workforce_reduction"
 ]
};
